"""Static TUI help topics for ``/help`` and ``/help <topic>``.

Sourced from README.md and chat.py slash-command behavior. No LLM.
"""

from __future__ import annotations

# Short one-line blurbs for /help topics
_TOPIC_BLURBS: dict[str, str] = {
    "topics": "full index of /help <topic> pages",
    "getting-started": "what to type: goals, feedback, ship, /new",
    "keys": "Ctrl+D ship, Ctrl+L paths, Ctrl+Q quit, paste",
    "phases": "Phase A plan, Phase B iterate, Phase C critique",
    "harness": "Chromium, probes, test report (always on)",
    "feedback-flows": "four meanings of “feedback” in this codebase",
    "patch": "<patch> vs <html_file>, revert, scoped turns",
    "feedback": "/feedback autonomous playtests",
    "rawfeedback": "/rawfeedback your typed lines verbatim",
    "vlm-critique": "/vlm-critique screenshot visual critic",
    "wait": "/wait step-mode between iters",
    "playbook": "/playbook memory/playbook.jsonl injection",
    "playtests": "behavior recipes for /feedback",
    "visual-playtests": "VLM checklists for /vlm-critique",
    "models": "/load /model2 /model3 /modelall /list",
    "gpu": "4×48GB Linux: GPU0 diffusers, 1–3 Ollama slots",
    "backend": "/backend ollama mlx openai anthropic",
    "mlx": "/launch in-process MLX, /unload mlx",
    "session": "/new /seed sticky staging, /reset /retry",
    "games": "/games curated prompt library, /games N to load",
    "revert": "/revert /rewind roll back HTML file",
    "ship": "done, /ship, Ctrl+D, clean streak",
    "knobs": "/iters /ctx /restarts /model-class",
    "mode": "/mode local_manual local_auto local_plus_review",
    "assets": "<assets> Z-Image-Turbo sprites",
    "sounds": "<sounds> Stable Audio sfx",
    "media": "redraw one asset or sound, no code change",
    "check": "/check on-demand visual review",
    "ref": "/ref attach reference image",
    "architect": "/architect vs /model2 --role architect",
    "allroles": "/allroles architect + vlm on one model",
    "prefill": "/prefill XML tag prefill",
    "double-screenshot": "/double-screenshot before/after PNGs",
    "iter-detail": "/iter-detail extra blocker lines",
    "inspect": "/status /log /open /audit",
    "goodgame": "/goodgame copy to goodgame/",
}

_HELP_TOPICS: dict[str, list[str]] = {
    "topics": [],  # filled below after all topics defined
    "getting-started": [
        "[bold cyan]Getting started — what to type when[/bold cyan]",
        "",
        "[b]First game[/b]  Describe what you want in the input box, press Enter.",
        "  Chromium opens beside the terminal; the agent plans (Phase A), then builds.",
        "",
        "[b]Small change after a shipped or paused game[/b]  Just type it — no slash.",
        "  e.g. [italic]ship is too slow, double thrust[/italic]",
        "",
        "[b]Stop and ship[/b]  [b]done[/b], [b]looks good[/b], [b]/ship[/b], or [b]Ctrl+D[/b].",
        "  Needs [b]2 consecutive clean iters[/b] before <done/> is accepted.",
        "  [dim]Ctrl+D drops queued feedback (incl. autonomous playtest) — re-send after ship if needed[/dim]",
        "",
        "[b]Brand-new unrelated game[/b]  [b]/new <goal>[/b]",
        "",
        "[b]Continue from existing HTML[/b]  [b]/seed <path>[/b] then [b]/new <goal>[/b]",
        "  Staging is [b]sticky[/b] across /new until /reset or bare /seed.",
        "",
        "[b]While agent runs[/b]  Type anytime — text queues for the next user-turn boundary.",
        "  [b]/wait on[/b] (TUI default): pauses after each iter; Enter or feedback to continue.",
        "",
        "[b]More detail[/b]  [b]/help topics[/b] · [b]/help feedback-flows[/b] · [b]/help phases[/b]",
    ],
    "keys": [
        "[bold cyan]Keyboard shortcuts[/bold cyan]",
        "",
        "  [b]Ctrl+D[/b]     ship current build (double within 2s force-quits)",
        "  [b]Ctrl+Q[/b]     quit TUI",
        "  [b]Ctrl+L[/b]     print session artifact paths (= [b]/log[/b])",
        "  [b]Ctrl+S[/b]     toggle mouse selection in agent log pane",
        "  [b]Ctrl+V[/b]     paste into input (terminal paste / Cmd+V on macOS)",
        "  [b]Enter[/b]      submit input · under [b]/wait on[/b], empty Enter = continue",
        "",
        "[dim]Avoid rebinding Ctrl+C — can leave shell without echo; run reset or stty sane[/dim]",
    ],
    "phases": [
        "[bold cyan]Agent phases (A → B → C)[/bold cyan]",
        "",
        "[b]Phase A — planning[/b] (1 turn)",
        "  Model emits [b]<plan>[/b], [b]<criteria>[/b], [b]<probes>[/b] (JS checks),",
        "  optional [b]<assets>[/b] / [b]<sounds>[/b]. Z-Image / Stable Audio run on GPU 0 when requested.",
        "",
        "[b]Phase B — build/iterate[/b] (up to [b]/iters[/b])",
        "  Stream reply → [b]<patch>[/b] preferred, else [b]<html_file>[/b] → micro-probes → Chromium",
        "  → test report → coaching for next turn. Failed iters: diagnose-then-fix.",
        "",
        "[b]Phase C — self-critique[/b] (after you signal done)",
        "  [b]<confirm_done/>[/b] to ship, or one more [b]<patch>[/b].",
        "  [b]/vlm-critique on[/b] attaches screenshot + visual checklist here.",
        "",
        "[b]Drivers[/b]  [b]chat.py[/b] (TUI) · [b]coder.py[/b] (headless CLI, same loop)",
    ],
    "harness": [
        "[bold cyan]Harness — always-on verification[/bold cyan]",
        "",
        "Every iter (no toggle):",
        "  • [b]Micro-probes[/b] — HTML structure, bracket balance, banned APIs, elision sentinels",
        "  • [b]Chromium[/b] — load game, console/page errors, RAF, frozen canvas, input smoke test",
        "  • [b]<probes>[/b] from Phase A — JS evaluated in page; failures set [b]ok=False[/b]",
        "  • [b]Screenshot[/b] per iter (for you and optional VLM paths)",
        "",
        "This is the core verifier — what makes the agent better than zero-shot.",
        "Not the same as [b]/feedback[/b] (extra playtests) or [b]/vlm-critique[/b] (visual critic).",
        "",
        "[b]Probes gate shipping[/b]  <done/> needs [b]ok=True[/b] and [b]2 clean iters[/b] in a row.",
        "  See [b]/help ship[/b] · [b]/help feedback-flows[/b]",
    ],
    "feedback-flows": [
        "[bold cyan]“Feedback” — four separate flows[/bold cyan]",
        "",
        "The word is overloaded. Four switches / behaviors:",
        "",
        "  [b]1. Machine bug feedback[/b]  Harness: Chromium, probes, test report.",
        "     [b]Always on[/b] — no toggle.",
        "",
        "  [b]2. Playbook retrieval[/b]  Top-K bullets from [b]memory/playbook.jsonl[/b].",
        "     Toggle: [b]/playbook on|off[/b] · default [b]ON[/b]",
        "",
        "  [b]3. Autonomous playtest[/b]  After clean iters → [b]memory/playtests.jsonl[/b].",
        "     Toggle: [b]/feedback on|off[/b] · default [b]ON[/b]",
        "     See [b]/help feedback[/b]",
        "",
        "  [b]4. Wrappers on YOUR typed lines[/b]  MEDIA-CHANGE / SCOPE / ORIENTATION classifiers.",
        "     Toggle: [b]/rawfeedback on|off[/b] · default [b]ON[/b] = verbatim (wrappers off)",
        "     See [b]/help rawfeedback[/b]",
        "",
        "[b]Visual critic[/b] is separate: [b]/vlm-critique[/b] · [b]/help vlm-critique[/b]",
    ],
    "feedback": [
        "[bold cyan]/feedback — autonomous playtest loop[/bold cyan]",
        "",
        "[b]What it is[/b]",
        "  After each [b]clean[/b] build iteration, the agent runs extra playtests from",
        "  [b]memory/playtests.jsonl[/b] (behavior recipes). Findings are queued as",
        "  [b][AUTONOMOUS PLAYTEST][/b] notes — same queue as if you had typed feedback.",
        "",
        "[b]What it is NOT[/b]",
        "  • Not Chromium console errors, probes, or the per-iter test report — [b]/help harness[/b]",
        "  • Not [b]/vlm-critique[/b] — [b]/help vlm-critique[/b]",
        "  • Not [b]/rawfeedback[/b] — [b]/help rawfeedback[/b]",
        "",
        "[b]Toggle[/b]  [b]/feedback on[/b] · default [b]ON[/b]  ·  bare [b]/feedback[/b] shows state",
        "  [b]/feedback off[/b] — harness + your notes + critic still run; only autonomous queue stops.",
        "",
        "[b]When to turn OFF[/b]  You only want harness + your own feedback.",
        "",
        "[b]Related[/b]  [b]/help playtests[/b] · [b]/help playbook[/b] · [b]/help feedback-flows[/b]",
    ],
    "vlm-critique": [
        "[bold cyan]/vlm-critique — screenshot visual critic[/bold cyan]",
        "  [dim]aliases: vlmcritique, vc[/dim]",
        "",
        "[b]What it is[/b]",
        "  Phase C (and related critic paths): attaches [b]screenshot[/b] for a [b]VLM[/b]",
        "  using [b]memory/visual_playtests.jsonl[/b] (mechanism-keyed checklists).",
        "  Catches look-and-feel: layout, sprites, facing — not just probe pass/fail.",
        "",
        "[b]What it is NOT[/b]",
        "  • Not [b]/feedback[/b] (behavior playtests) — [b]/help feedback[/b]",
        "  • Not [b]/check[/b] (you trigger review) — [b]/help check[/b]",
        "  • Not the always-on harness — [b]/help harness[/b]",
        "",
        "[b]Toggle[/b]  default [b]OFF[/b]  ·  needs VLM on critic slot or slot 1",
        "",
        "[b]/wait interaction[/b]  [b]/wait on[/b] auto-disables vlm-critique (you're the reviewer).",
        "  Restored on [b]/wait off[/b] unless you set vlm-critique explicitly mid-wait.",
        "",
        "[b]Auto-staff[/b]  [b]/model2 … --role critic[/b] or VLM on any slot can auto-enable",
        "  (status shows [auto]); override with [b]/vlm-critique off[/b].",
        "",
        "[b]Related[/b]  [b]/help visual-playtests[/b] · [b]/double-screenshot[/b] · [b]/allroles[/b]",
    ],
    "rawfeedback": [
        "[bold cyan]/rawfeedback — your typed lines verbatim[/bold cyan]",
        "  [dim]aliases: raw-feedback, raw[/dim]",
        "",
        "[b]ON[/b] (default): your feedback goes to the model without classifier wrappers.",
        "[b]/rawfeedback off[/b]: opt into MEDIA-CHANGE, ORIENTATION, SCOPE ARBITRATION, asset-stem mapping.",
        "",
        "[b]Unaffected when off or on[/b]  Machine test reports, console errors, probes,",
        "  playbook retrieval, [b]/feedback[/b] autonomous playtest, [b]/vlm-critique[/b].",
        "",
        "[b]Why default ON[/b]  Wrappers historically misrouted user guidance.",
        "  See [b]/help feedback-flows[/b] · [b]/help media[/b] for asset-only phrasing.",
    ],
    "wait": [
        "[bold cyan]/wait — step-mode between iterations[/bold cyan]",
        "",
        "[b]ON[/b] (TUI default): agent pauses after each iter; you inspect Chromium,",
        "  type feedback or press Enter to continue.",
        "",
        "[b]OFF[/b]: loop runs continuously; coaching queues for next coder turn.",
        "",
        "[b]Interaction[/b]",
        "  • [b]/wait on[/b] → auto-disables [b]/vlm-critique[/b] (you're the visual reviewer)",
        "  • [b]/check[/b] with wait ON: suggestion prefilled in input; wait OFF: auto-queues",
        "  • [b]/mode local_manual[/b] sets wait ON; [b]local_auto[/b] sets wait OFF",
        "",
        "[b]Usage[/b]  [b]/wait on[/b] · [b]/wait off[/b] · bare [b]/wait[/b] toggles",
    ],
    "playbook": [
        "[bold cyan]/playbook — cross-session rules of thumb[/bold cyan]",
        "  [dim]alias: /memory[/dim]",
        "",
        "[b]What[/b]  Retrieves top-K bullets from [b]memory/playbook.jsonl[/b] (hand-curated).",
        "  Weighted by keyword overlap × quality score. Model may [b]<lookup_bullet>id[/b].",
        "",
        "[b]Toggle[/b]  [b]/playbook on|off[/b] · default [b]ON[/b] in TUI",
        "  Turn off to A/B whether bullets help your model size.",
        "",
        "[b]Not the same as[/b]",
        "  • [b]playtests.jsonl[/b] — [b]/help playtests[/b] (autonomous behavior checks)",
        "  • [b]visual_playtests.jsonl[/b] — [b]/help visual-playtests[/b] (VLM checklists)",
        "",
        "[b]/audit[/b]  Per-bullet stats from trace history (fires, pass-rate, avg iter).",
    ],
    "playtests": [
        "[bold cyan]Behavior playtests (memory/playtests.jsonl)[/bold cyan]",
        "",
        "Genre-free [b]behavior[/b] recipes used when [b]/feedback[/b] is ON.",
        "After a [b]clean[/b] iter, matcher picks recipes from goal + plan + asset names.",
        "Failures queue as [b][AUTONOMOUS PLAYTEST][/b] feedback.",
        "",
        "Hand-edited JSONL (like playbook). Append a line to add a recipe — no Python change.",
        "",
        "Contrast [b]visual_playtests.jsonl[/b] — [b]/help visual-playtests[/b] (screenshot/VLM).",
    ],
    "visual-playtests": [
        "[bold cyan]Visual playtests (memory/visual_playtests.jsonl)[/bold cyan]",
        "",
        "Mechanism-keyed [b]visual[/b] checklists for [b]/vlm-critique[/b] and structured critic.",
        "Matcher uses goal + plan + asset names (e.g. maze wording → grid-navigation recipe).",
        "",
        "Some recipes include [b]auto-probes[/b] — extra JS assertions (facing, in-wall, bounds).",
        "Trace: [b]visual_playtest_recipe_used[/b], [b]visual_playtest_auto_probes_injected[/b].",
        "",
        "Closed yes/no checklist beats open-ended “what's wrong?” for small VLMs.",
        "",
        "Contrast [b]playtests.jsonl[/b] — [b]/help playtests[/b] (behavior, /feedback).",
    ],
    "patch": [
        "[bold cyan]Patches, rewrites, and scoped turns[/bold cyan]",
        "",
        "[b]<patch>[/b]  SEARCH/REPLACE blocks — preferred after iter 1 when game works.",
        "  [b]<html_file>[/b]  full rewrite — OK for first build; risky once [b]best.html[/b] exists.",
        "",
        "[b]Failed iter[/b]  diagnose-then-fix prompt. [b]best_of_n[/b] tries up to 3 patch candidates.",
        "",
        "[b]Scoped feedback[/b]  “only X”, “no code changes” → enforced modes:",
        "  • [b]single_patch[/b] — one small patch, no full rewrite",
        "  • [b]media_only[/b] — <assets>/<sounds> only, existing names",
        "",
        "[b]Blocker-first[/b]  Code feedback deferred while [b]ok=False[/b]; media regen can still run on GPU 0.",
        "  Third repeat of same ask escalates through.",
        "",
        "[b]Broken build?[/b]  [b]/revert[/b] — [b]/help revert[/b] (file only, not conversation)",
    ],
    "models": [
        "[bold cyan]Models — coder and sidecar slots[/bold cyan]",
        "",
        "[b]Coder (required)[/b]  [b]/load <N|name>[/b] or [b]/model[/b] — writes plan, HTML, patches.",
        "  Sticky across [b]/new[/b].",
        "",
        "[b]/list[/b]  Ollama + MLX (+ cloud if API keys set). [b]*[/b] = loaded in VRAM;",
        "  [b]← active[/b] = bound to this session.",
        "",
        "[b]/model2[/b]  Sidecar slot 2 · [b]--role critic|architect[/b]",
        "[b]/model3[/b]  Sidecar slot 3",
        "  VLMs default critic; text models default architect. Staging enables matching features.",
        "",
        "[b]/modelall <N>[/b]  Same model on all three Ollama slots; bare clears all three.",
        "",
        "[b]1-model[/b]  Only /load — same model does everything (+ harness).",
        "[b]3-model[/b]  /load + /model2 architect + /model3 critic — cleanest split.",
        "",
        "[b]See also[/b]  [b]/help gpu[/b] · [b]/help backend[/b] · [b]/help mlx[/b] · [b]/help architect[/b]",
    ],
    "gpu": [
        "[bold cyan]GPU layout (4×48 GB Linux workstation)[/bold cyan]",
        "",
        "When [b]/model[/b], [b]/model2[/b], [b]/model3[/b] are Ollama and autopin applies:",
        "  [b]GPU 0[/b]  TUI + Z-Image + Stable Audio + SD-Turbo img2img",
        "  [b]GPU 1[/b]  Ollama [b]11434[/b] — coder (slot 1)",
        "  [b]GPU 2[/b]  Ollama [b]11435[/b] — model2",
        "  [b]GPU 3[/b]  Ollama [b]11436[/b] — model3",
        "",
        "Override: [b]OLLAMA_HOST2[/b] / [b]OLLAMA_HOST3[/b], [b]AGENT_NO_AUTO_OLLAMA_PIN=1[/b],",
        "  [b]DIFFUSER_CUDA_DEVICE[/b] for diffusers GPU.",
        "",
        "[b]Mac / MLX[/b]  In-process model — no per-GPU Ollama daemons. [b]/help mlx[/b]",
        "",
        "[b]Single GPU[/b]  Multi-slot features gate on independence; fall back to one daemon.",
        "  Status panel shows placement per slot.",
    ],
    "backend": [
        "[bold cyan]/backend — LLM provider[/bold cyan]",
        "",
        "  [b]auto[/b]     probe MLX + Ollama (MLX wins on Mac when both available)",
        "  [b]ollama[/b]   HTTP daemons (multi-slot on 4-GPU box)",
        "  [b]mlx[/b]      in-process on Apple Silicon / explicit MLX path",
        "  [b]openai[/b]   needs [b]OPENAI_API_KEY[/b] — billable",
        "  [b]anthropic[/b] needs [b]ANTHROPIC_API_KEY[/b] — billable",
        "",
        "Cloud is never silent — explicit backend or [b]/check claude[/b] / [b]/check gpt-5[/b].",
        "",
        "Env: [b]LLM_BACKEND[/b], [b]OLLAMA_MODEL[/b], [b]MLX_MODEL[/b], [b]CODING_BOX_NUM_CTX[/b]",
    ],
    "mlx": [
        "[bold cyan]MLX — in-process local models[/bold cyan]",
        "",
        "[b]/launch <N|name|path>[/b]  Stage MLX model for next [b]/new[/b].",
        "  Loads into Python VRAM on first request (~30–60s cold).",
        "",
        "[b]/unload mlx[/b]  Drop in-process MLX weights.",
        "",
        "Mac default backend is often MLX. No separate mlx_lm.server — same process as chat.py.",
        "",
        "Stall on MLX does not auto-fallback to Ollama — [b]/backend ollama[/b] + [b]/load[/b] to switch.",
        "",
        "Env: [b]MLX_MODEL[/b], [b]MLX_MODELS_DIR[/b], [b]MLX_PREFILL_STEP_SIZE[/b], [b]MLX_MAX_TOKENS[/b]",
    ],
    "session": [
        "[bold cyan]Session lifecycle and sticky staging[/bold cyan]",
        "",
        "[b]/new <goal>[/b]     New session; uses staged seed, models, iters, ctx.",
        "[b]/seed <path>[/b]   Baseline .html for next /new · bare [b]/seed[/b] clears.",
        "  Snapshots under [b]games/snapshots/[/b] resolve to canonical [b]games/<name>.html[/b].",
        "[b]/reset[/b]         Wipe staged seed, models, iters, ctx, mode profile — not running agent.",
        "[b]/retry[/b]         Re-run after bad model; keeps game file + trace.",
        "",
        "[b]Sticky across /new[/b]  /seed, /load, /iters, /ctx, /restarts, /model-class, /mode, toggles.",
        "  Clear individually (bare command) or [b]/reset[/b] everything.",
        "",
        "[b]Artifacts[/b]  under [b]games/[/b] — html, traces, *_assets/, *_screenshots/",
        "[b]/log[/b]  print paths · [b]/help inspect[/b]",
    ],
    "games": [
        "[bold cyan]Curated game-prompt library[/bold cyan]",
        "",
        "[b]/games[/b]          List the numbered prompts (also /library, /prompts).",
        "[b]/games <N>[/b]      Load prompt #N into the input box.",
        "  Press [b]Enter[/b] to build it, or edit the text first.",
        "",
        "Hand-curated, ships in [b]memory/prompt_library.jsonl[/b] — one JSON",
        "object per line ([b]n[/b], [b]name[/b], [b]title[/b], [b]prompt[/b]). Add your own by",
        "appending a line. Each prompt names the entity AND every action pose,",
        "so the planner generates a frame per move up front.",
        "",
        "[dim]A running session is refused — ship it (Ctrl+D) first.[/dim]",
    ],
    "revert": [
        "[bold cyan]/revert — roll back the game file[/bold cyan]",
        "  [dim]alias: /rewind[/dim]",
        "",
        "[b]/revert[/b]       Restore [b]best.html[/b] from last [b]clean[/b] iter snapshot.",
        "[b]/revert N[/b]     Restore iter [b]N[/b] specifically.",
        "",
        "[b]Does NOT reset[/b]  iter counter or conversation — only the on-disk HTML.",
        "  Your next feedback applies to the reverted file.",
        "",
        "Use when the model broke something — faster than typing “undo that”.",
        "Emits [b]user_revert[/b] trace event.",
    ],
    "ship": [
        "[bold cyan]Shipping — done, /ship, Ctrl+D[/bold cyan]",
        "",
        "[b]Requirements for <done/>[/b]",
        "  • Latest test report [b]ok=True[/b]",
        "  • [b]2 consecutive clean iters[/b] (default min clean streak)",
        "",
        "[b]Ways to ship[/b]  Type [b]done[/b] / [b]looks good[/b] · [b]/ship[/b] · [b]Ctrl+D[/b]",
        "",
        "[b]Phase C[/b]  After <done/>, one critique turn: [b]<confirm_done/>[/b] or final <patch>.",
        "",
        "[b]Ctrl+D[/b]  Finishes current turn cleanly; drops [b]queued[/b] feedback including autonomous.",
        "  Re-send feedback after ship if still wanted.",
        "",
        "[b]/goodgame[/b]  Copy shipped build to [b]goodgame/[/b] — [b]/help goodgame[/b]",
    ],
    "knobs": [
        "[bold cyan]Run knobs (sticky)[/bold cyan]",
        "",
        "[b]/iters <N>[/b]  Max iterations per session / extension.",
        "",
        "[b]/ctx [N|100k|131k|262k|full][/b]  Ollama context / KV size. Default [b]100k[/b].",
        "  Bare [b]/ctx[/b] shows current. Ollama reloads on change — preload:",
        "  [dim]ollama run --ctx-size N <model>[/dim]",
        "",
        "[b]/restarts <N>[/b]  Full restarts when iter-1 score < 60. Default [b]2[/b]; [b]1[/b] = off.",
        "",
        "[b]/model-class auto|small|mid|large[/b]  System prompt trim.",
        "  [b]small[/b] ~5KB lean schema; [b]mid[/b] keeps assets/sounds; [b]large[/b] full prompt.",
    ],
    "mode": [
        "[bold cyan]/mode — run contract presets[/bold cyan]",
        "",
        "[b]local_manual[/b]  wait ON · you checkpoint each iter",
        "[b]local_auto[/b]    wait OFF · continuous loop",
        "[b]local_plus_review with <model> [--auto-apply][/b]",
        "     wait OFF + reviewer hook; auto-apply only when wait OFF",
        "[b]custom[/b]          clear profile; manual /wait /check",
        "",
        "Profiles clear staged cloud backend for local-first.",
        "Bare [b]/mode[/b] shows current profile.",
    ],
    "assets": [
        "[bold cyan]Sprites — <assets> and Z-Image-Turbo[/bold cyan]",
        "",
        "Phase A (or mid-session): model emits [b]<assets>[/b] JSON list →",
        "  Z-Image-Turbo PNGs (~768²) beside the .html, chroma-key → RGBA.",
        "",
        "Nudge in goal: [italic]sprite, pixel-art, icon, texture, cool art[/italic]",
        "",
        "[b]Animation[/b]  [b]from_image[/b] + [b]strength[/b] on an asset → SD-Turbo img2img chain.",
        "  Nudge: [italic]walk cycle, animated, two-frame, flap[/italic]",
        "",
        "[b]Opt out of preload[/b]  [b]SKIP_DIFFUSER_PRELOAD=1[/b] at launch",
        "",
        "[b]Redraw one asset[/b]  — [b]/help media[/b]",
    ],
    "sounds": [
        "[bold cyan]Sound — <sounds> and Stable Audio Open[/bold cyan]",
        "",
        "Phase A: [b]<sounds>[/b] → OGG files beside the .html.",
        "Nudge in goal: [italic]sound, audio, sfx, music, chiptune[/italic]",
        "",
        "Regenerate one: [b]/help media[/b]",
        "",
        "Smoke: [b]scripts/_smoke_audio.py[/b]",
    ],
    "media": [
        "[bold cyan]Redraw ONE asset or sound (no code change)[/bold cyan]",
        "",
        "[b]Asset template[/b]",
        "  redraw the [italic]<name>[/italic] asset as [italic]<description>[/italic], no code changes",
        "",
        "[b]Sound template[/b]",
        "  remake the [italic]<name>[/italic] sound as [italic]<description>[/italic], only the audio",
        "",
        "Triggers MEDIA-CHANGE path: model emits <assets>/<sounds> with [b]same name[/b],",
        "  PNG/OGG replaced in place; draw/load code unchanged; code-rewrite gate closed.",
        "",
        "Works even when last iter failed (GPU 0 path parallel to coder blocker fixes).",
    ],
    "check": [
        "[bold cyan]/check — on-demand visual review[/bold cyan]",
        "",
        "One-shot VLM call on [b]latest screenshot[/b] — does not change coder model.",
        "",
        "[b]/check[/b]           active session VLM (must be running + screenshot exists)",
        "[b]/check <N>[/b]       model #N from [b]/list[/b] (MLX/OpenAI/Anthropic VLM rows)",
        "[b]/check claude[/b]    Anthropic · [b]/check gpt-5[/b] OpenAI · local MLX VLM by name",
        "",
        "[b]/wait ON[/b]   prefills suggestion in input for edit + Enter",
        "[b]/wait OFF[/b]  auto-queues coaching to next coding turn",
        "[b]--apply[/b]     force queue even with wait ON",
        "",
        "Contrast [b]/vlm-critique[/b] (automatic Phase C) — [b]/help vlm-critique[/b]",
    ],
    "ref": [
        "[bold cyan]/ref — reference image for next turn[/bold cyan]",
        "",
        "[b]/ref <path>[/b]  Attach PNG/JPEG/WebP to the [b]next[/b] user message (VLM backends).",
        "  Works before [b]/new[/b]. Say e.g. “make the game look like this” on the next line.",
        "",
        "Drag file into terminal to paste path. Session clears ref after one use.",
    ],
    "architect": [
        "[bold cyan]/architect — planning split[/bold cyan]",
        "  [dim]alias: /arch[/dim]",
        "",
        "[b]/architect on[/b]  Complex first-builds: separate planning pass before coder writes HTML.",
        "  Default [b]OFF[/b].",
        "",
        "[b]Distinct from[/b]  [b]/model2 … --role architect[/b] — assigns [b]which GPU/model[/b] does architect role.",
        "  Staging architect on model2 can [b]auto-enable[/b] architect-split ([auto] in status).",
        "",
        "[b]/allroles[/b]  Enables architect + vlm-critique on [b]one[/b] loaded model — [b]/help allroles[/b]",
    ],
    "allroles": [
        "[bold cyan]/allroles — one model, architect + visual critic[/bold cyan]",
        "",
        "Toggles [b]/architect on[/b] and [b]/vlm-critique on[/b] together for your single [b]/load[/b] model.",
        "No /model2 /model3 required. Needs [b]VLM-capable[/b] model for screenshot critique.",
        "",
        "Staged sidecar slots still win when present. [b]/reset[/b] clears the bundle.",
        "Bare [b]/allroles[/b] flips on/off.",
    ],
    "prefill": [
        "[bold cyan]/prefill — assistant tag prefill[/bold cyan]",
        "",
        "Forces assistant to start with [b]<plan>[/b], [b]<diagnose>[/b], etc.",
        "Reduces preamble and improves XML compliance. Default [b]ON[/b].",
        "",
        "[b]/prefill off[/b]  if your model fights prefill tags.",
    ],
    "double-screenshot": [
        "[bold cyan]/double-screenshot — motion debug PNGs[/bold cyan]",
        "  [dim]aliases: ds, doublescreenshot[/dim]",
        "",
        "Captures startup + post-input screenshots. Default [b]OFF[/b].",
        "Most useful with [b]/vlm-critique on[/b] so critic can compare movement.",
    ],
    "iter-detail": [
        "[bold cyan]/iter-detail — verbose iter decision line[/bold cyan]",
        "",
        "Optional expanded blocker detail after each iter. Default [b]OFF[/b].",
        "[b]/iter-detail on|off[/b]",
    ],
    "inspect": [
        "[bold cyan]Inspection commands[/bold cyan]",
        "",
        "[b]/status[/b]   model, phase, iter, staged picks, ctx, paths, toggles",
        "[b]/log[/b]      all artifact paths [dim](Ctrl+L; aliases /paths /files)[/dim]",
        "[b]/open[/b]     open current game HTML in default browser",
        "[b]/clear[/b]    clear agent log pane only",
        "[b]/audit[/b]    playbook bullet earnings from traces",
        "[b]/list[/b]     model inventory",
    ],
    "goodgame": [
        "[bold cyan]/goodgame — save a keeper[/bold cyan]",
        "  [dim]alias: /good[/dim]",
        "",
        "Copies [b]best.html[/b] (or live .html) plus [b]*_assets/[/b] and [b]*_sounds/[/b]",
        "  into [b]goodgame/[/b] (tracked in git, not under games/ gitignore).",
        "",
        "Does not run git commands. Use when you want to keep a reference build.",
    ],
}

# Build /help topics index page
_topics_index: list[str] = [
    "[bold cyan]Help topics — /help <name>[/bold cyan]",
    "",
    "[dim]No LLM — static pages from README + chat.py behavior.[/dim]",
    "",
]
_categories = [
    ("Start here", ["getting-started", "keys", "topics", "phases", "harness", "feedback-flows", "patch"]),
    ("Feedback & verification", ["feedback", "rawfeedback", "vlm-critique", "wait", "playbook", "playtests", "visual-playtests", "check"]),
    ("Models & GPUs", ["models", "gpu", "backend", "mlx"]),
    ("Session & shipping", ["session", "games", "revert", "ship", "knobs", "mode", "goodgame"]),
    ("Assets & media", ["assets", "sounds", "media", "ref"]),
    ("Feature toggles", ["architect", "allroles", "prefill", "double-screenshot", "iter-detail"]),
    ("Inspection", ["inspect"]),
]
for _title, _ids in _categories:
    _topics_index.append(f"[bold]{_title}[/bold]")
    for _tid in _ids:
        if _tid == "topics":
            continue
        _blurb = _TOPIC_BLURBS.get(_tid, "")
        _topics_index.append(f"  [b]/help {_tid}[/b]  [dim]{_blurb}[/dim]")
    _topics_index.append("")

_HELP_TOPICS["topics"] = _topics_index

# User-typed topic -> canonical topic_id
_TOPIC_ALIASES: dict[str, str] = {
    "topics": "topics",
    "index": "topics",
    "list": "topics",
    "all": "topics",
    "getting-started": "getting-started",
    "start": "getting-started",
    "begin": "getting-started",
    "workflow": "getting-started",
    "keys": "keys",
    "keyboard": "keys",
    "shortcuts": "keys",
    "phases": "phases",
    "phase": "phases",
    "abc": "phases",
    "harness": "harness",
    "verifier": "harness",
    "probes": "harness",
    "test-report": "harness",
    "feedback-flows": "feedback-flows",
    "flows": "feedback-flows",
    "four-flows": "feedback-flows",
    "overload": "feedback-flows",
    "patch": "patch",
    "patches": "patch",
    "html-file": "patch",
    "feedback": "feedback",
    "autonomous": "feedback",
    "playtest": "playtests",
    "playtests": "playtests",
    "autonomous-playtest": "feedback",
    "autonomous-feedback": "feedback",
    "vlm-critique": "vlm-critique",
    "vlm": "vlm-critique",
    "vlmcritique": "vlm-critique",
    "vc": "vlm-critique",
    "critique": "vlm-critique",
    "visual": "visual-playtests",
    "visual-playtests": "visual-playtests",
    "visual-playtest": "visual-playtests",
    "vlm_critique": "vlm-critique",
    "rawfeedback": "rawfeedback",
    "raw": "rawfeedback",
    "raw-feedback": "rawfeedback",
    "wait": "wait",
    "step": "wait",
    "step-mode": "wait",
    "playbook": "playbook",
    "memory": "playbook",
    "models": "models",
    "model": "models",
    "load": "models",
    "model2": "models",
    "model3": "models",
    "modelall": "models",
    "slots": "models",
    "gpu": "gpu",
    "gpus": "gpu",
    "topology": "gpu",
    "four-gpu": "gpu",
    "backend": "backend",
    "ollama": "backend",
    "mlx": "mlx",
    "launch": "mlx",
    "session": "session",
    "new": "session",
    "seed": "session",
    "reset": "session",
    "retry": "session",
    "sticky": "session",
    "games": "games",
    "game": "games",
    "library": "games",
    "prompts": "games",
    "revert": "revert",
    "rewind": "revert",
    "undo": "revert",
    "ship": "ship",
    "done": "ship",
    "ctrl-d": "ship",
    "knobs": "knobs",
    "iters": "knobs",
    "ctx": "knobs",
    "context": "knobs",
    "restarts": "knobs",
    "model-class": "knobs",
    "mode": "mode",
    "profile": "mode",
    "assets": "assets",
    "sprites": "assets",
    "z-image": "assets",
    "sounds": "sounds",
    "audio": "sounds",
    "sfx": "sounds",
    "media": "media",
    "redraw": "media",
    "asset": "media",
    "check": "check",
    "judge": "check",
    "ref": "ref",
    "reference": "ref",
    "architect": "architect",
    "arch": "architect",
    "allroles": "allroles",
    "all-roles": "allroles",
    "prefill": "prefill",
    "double-screenshot": "double-screenshot",
    "doublescreenshot": "double-screenshot",
    "ds": "double-screenshot",
    "iter-detail": "iter-detail",
    "iterdetail": "iter-detail",
    "inspect": "inspect",
    "status": "inspect",
    "log": "inspect",
    "audit": "inspect",
    "open": "inspect",
    "goodgame": "goodgame",
    "good": "goodgame",
}


def normalize_help_topic(raw: str) -> str | None:
    """Map user arg to topic_id, or None if empty / unknown."""
    key = (raw or "").strip().lower().replace("_", "-")
    if not key:
        return None
    return _TOPIC_ALIASES.get(key)


def list_help_topics() -> list[str]:
    """Canonical topic ids (excludes duplicate alias entries)."""
    return sorted(_HELP_TOPICS.keys())


def help_topic_lines(topic_id: str) -> list[str] | None:
    return _HELP_TOPICS.get(topic_id)


def help_topics_index_lines() -> list[str]:
    """Short pointer block appended to the main /help overview."""
    return [
        "",
        "[bold cyan]── help topics (detail, no LLM) ──[/bold cyan]",
        "  [b]/help topics[/b]              full index of all topic pages",
        "  [b]/help feedback-flows[/b]    four meanings of “feedback”",
        "  [b]/help feedback[/b]          [b]/help vlm-critique[/b]  [b]/help rawfeedback[/b]",
        "  [b]/help getting-started[/b]   goals, ship, /new, /seed",
        "  [b]/help models[/b]  [b]gpu[/b]  [b]session[/b]  [b]assets[/b]  [b]check[/b]  …",
        "  [dim]unknown topic lists names · /help topics for complete list[/dim]",
    ]


def format_unknown_topic_message(arg: str) -> list[str]:
    """Lines to log when topic name is not recognized."""
    names = ", ".join(t for t in list_help_topics() if t != "topics")
    return [
        f"unknown help topic {arg.strip()!r}",
        f"topics: {names}",
        "usage: /help  |  /help topics  |  /help feedback",
    ]
