"""One prompt per game or graphic.

Each title in TOP_GAMES is one complete working version. A line from
ideas_1000.txt is added only when that game is not already in TOP_GAMES.
Openings rotate. The same game is not written twice.

    .venv/bin/python fine_tunning/expand_ideas.py
"""
from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

OPENERS = (
    'Write me {body}.',
    'Make {body}.',
    'Build {body}.',
    'Create {body}.',
    'Code {body}.',
    'Give me {body}.',
    'I want {body}.',
    'Make me {body}.',
    'Build me {body}.',
    'Can you make {body}?',
    'Can you build {body}?',
    'Please make {body}.',
    'Please build {body}.',
    "I'd like {body}.",
    'Show me {body}.',
    'Put together {body}.',
    'How about {body}?',
    'Could you make {body}?',
    "Let's make {body}.",
)

HERE = Path(__file__).resolve().parent

# One entry per acclaimed game. A year is kept only when two games share a name.
TOP_GAMES = (
    'Tetris',
    'Resident Evil 4',
    'The Last of Us',
    'Half-Life 2',
    'The Legend of Zelda: Breath of the Wild',
    'The Witcher 3: Wild Hunt',
    'Hades',
    'The Legend of Zelda: Ocarina of Time',
    'Super Mario 64',
    'Mass Effect 2',
    'The Legend of Zelda: A Link to the Past',
    'BioShock',
    'Grand Theft Auto V',
    'Super Metroid',
    'Shadow of the Colossus',
    'God of War (2018)',
    'Street Fighter II',
    'Call of Duty 4: Modern Warfare',
    'Final Fantasy VII',
    'World of Warcraft',
    'Red Dead Redemption',
    'Doom (1993)',
    'The Elder Scrolls V: Skyrim',
    'Halo: Combat Evolved',
    'GoldenEye 007',
    'Red Dead Redemption 2',
    'Chrono Trigger',
    'Super Mario World',
    'Castlevania: Symphony of the Night',
    'Bloodborne',
    'Metal Gear Solid',
    'Portal',
    'Uncharted 2: Among Thieves',
    'Journey',
    'Portal 2',
    'Minecraft',
    'Dark Souls',
    'Super Mario Bros. 3',
    'Metroid Prime',
    'StarCraft',
    'Super Mario Kart',
    'Deus Ex',
    'Star Wars: Knights of the Old Republic',
    'Final Fantasy VI',
    'Disco Elysium',
    'The Last of Us Part II',
    'Rock Band',
    "Tony Hawk's Pro Skater",
    'Diablo II',
    'Half-Life',
    'Counter-Strike',
    'Silent Hill 2',
    'Super Mario Bros.',
    'Pokemon Blue/Red/Yellow',
    'Inside',
    'Metal Gear Solid 3: Snake Eater',
    'Tomb Raider (1996)',
    'Ico',
    'Grand Theft Auto III',
    'Sonic the Hedgehog',
    'Super Smash Bros. Ultimate',
    'Fallout 3',
    'Donkey Kong',
    'Animal Crossing: New Horizons',
    'Super Mario Odyssey',
    'Celeste',
    'Stardew Valley',
    'Undertale',
    'Ms. Pac-Man',
    'Batman: Arkham City',
    'Super Mario Galaxy 2',
    'EarthBound',
    'System Shock 2',
    'Overwatch',
    'Super Smash Bros. Melee',
    'SimCity',
    'Pac-Man',
    'The Legend of Zelda: The Wind Waker',
    'Grim Fandango',
    'SimCity 2000',
    'Mega Man 2',
    "Super Mario World 2: Yoshi's Island",
    'Resident Evil',
    'League of Legends',
    'The Sims',
    'The Legend of Zelda',
    'Space Invaders',
    'Batman: Arkham Asylum',
    'Okami',
    'Grand Theft Auto IV',
    'Braid',
    'The Walking Dead',
    'The Secret of Monkey Island',
    'Outer Wilds',
    'Lemmings',
    'Final Fantasy Tactics',
    'Prince of Persia: The Sands of Time',
    'Civilization IV',
    'NBA Jam',
    'Galaga',
    'Persona 5',
    'Super Mario Galaxy',
    "Mike Tyson's Punch-Out!!",
    'X-COM: UFO Defense',
    'Secret of Mana',
    'Half-Life: Alyx',
    'Grand Theft Auto: Vice City',
    'Grand Theft Auto: San Andreas',
    'Planescape: Torment',
    'Return of the Obra Dinn',
    'Fortnite',
    'Quake',
    'Persona 4',
    "Assassin's Creed II",
    'Advance Wars',
    'Sonic the Hedgehog 2',
    'God of War (2005)',
    'Mario Kart 8',
    'Spelunky',
    'Gauntlet',
    'Zork',
    'Fire Emblem: Three Houses',
    'Gran Turismo',
    'Guitar Hero',
    'Civilization',
    'Age of Empires II: The Age of Kings',
    'Left 4 Dead 2',
    'Pong',
    'Madden NFL Football',
    'Burnout 3: Takedown',
    'Team Fortress 2',
    'Genshin Impact',
    'Contra',
    'Warcraft II: Tides of Darkness',
    'Day of the Tentacle',
    'Resident Evil 2',
    'Wii Sports',
    'Baldur’s Gate II: Shadows of Amn',
    'Soul Calibur',
    'Rocket League',
    'Crusader Kings III',
    'Myst',
    'The Elder Scrolls IV: Oblivion',
    'Star Wars: TIE Fighter',
    'Rez',
    'Civilization II',
    'Wolfenstein 3D',
    'Halo 3',
    'Limbo',
    'Asteroids',
    'Double Dragon',
    'Apex Legends',
    'Dishonored',
    "The Legend of Zelda: Majora's Mask",
    'Metroid',
    'Dota 2',
    'Thief: The Dark Project',
    'Civilization V',
    'Spider-Man',
    'Hotline Miami',
    'Left 4 Dead',
    'Elite',
    'Pitfall!',
    'Shenmue',
    'NHL Hockey',
    'Nier: Automata',
    'Mortal Kombat II',
    'Pokemon Gold/Silver/Crystal',
    'Donkey Kong Country',
    'Prince of Persia',
    'XCOM: Enemy Unknown',
    'Divinity: Original Sin II',
    'Command & Conquer: Red Alert',
    'Defender',
    'Quake III Arena',
    'Doom II',
    'Into the Breach',
    'FIFA Soccer',
    'Diablo',
    'Ultima Online',
    'Spelunky 2',
    'Command & Conquer',
    'Star Fox 64',
    'The Elder Scrolls III: Morrowind',
    '13 Sentinels: Aegis Rim',
    'The Legend of Zelda: Link’s Awakening',
    'Halo 2',
    'Destiny',
    'Dead Space',
    'Robotron 2084',
    'Bayonetta 2',
    'Tecmo Bowl',
    'Ori and the Will of the Wisps',
    'Fallout',
    'Final Fantasy X',
    'Gran Turismo 3: A-Spec',
    'EverQuest',
    'Gears of War',
    'Doom Eternal',
    'Hearthstone: Heroes of Warcraft',
    'Untitled Goose Game',
    'Fallout 2',
    'Fez',
    "Tom Clancy's Splinter Cell: Chaos Theory",
    'Final Fantasy IV',
    'Tekken 3',
    'StarCraft II: Wings of Liberty',
    'The Oregon Trail',
    'Papers Please',
    'Mortal Kombat',
    'Street Fighter IV',
    'Homeworld',
    'Katamari Damacy',
    'Streets of Rage 2',
    'Super Meat Boy',
    "Monkey Island 2: LeChuck's Revenge",
    'Sensible Soccer',
    'Warcraft III: Reign of Chaos',
    'Metal Gear Solid 2: Sons of Liberty',
    'Animal Crossing',
    'Castlevania',
    'Mass Effect',
    'Psychonauts',
    'Battlefield 1942',
    'Rome: Total War',
    'Dishonored 2',
    'Dance Dance Revolution',
    'Thief II: The Metal Age',
    'Gone Home',
    'Doom (2016)',
    'Duke Nukem 3D',
    'Ninja Gaiden (1988)',
    'Gears of War 2',
    'Star Wars: The Arcade Game',
    'Monster Hunter: World',
    'Fire Emblem: Awakening',
    'Super Bomberman',
    "Uncharted 4: A Thief's End",
    'Ultima IV: Quest of the Avatar',
    'Horizon: Zero Dawn',
    'Street Fighter III',
    "Devil May Cry 3: Dante's Awakening",
    'Bayonetta',
    'Phantasy Star IV',
    'Max Payne',
    'Dragon Quest Builders 2',
    'Sam & Max Hit the Road',
    'Soul Calibur II',
    'Ultima Underworld: The Stygian Abyss',
    'Jet Grind Radio',
    'Borderlands 2',
    'Pro Evolution Soccer',
    'OutRun',
    'Star Fox',
    'Banjo-Kazooie',
    'Sonic CD',
    'Ikaruga',
    'Hitman: Blood Money',
    'Out of This World',
    'Sekiro: Shadows Die Twice',
    'Death Stranding',
    'Pokemon Sword/Shield',
    'Star Wars Jedi: Fallen Order',
    'Quake II',
    'Ultima VII: The Black Gate',
    'Star Wars: X-Wing',
    'Mega Man X',
    'The Witness (2016)',
    'WarioWare Inc: Mega Microgames!',
    'Unreal Tournament',
    'Beyond Good & Evil',
    'Populous',
    'BioShock Infinite',
    'Wipeout',
    'Bubble Bobble',
    "Baldur's Gate",
    'Xenoblade Chronicles',
    'Lode Runner',
    'Wing Commander',
    'Gunstar Heroes',
    'Nights Into Dreams',
    'Super Mario RPG: Legend of the Seven Stars',
    'Suikoden II',
    'Fallout: New Vegas',
    'Crazy Taxi',
    'Speedball 2: Brutal Deluxe',
    'Adventure',
    'Pirates!',
    'Geometry Wars: Retro Evolved',
    'Super Smash Bros.',
    'Age of Empires',
    'Mario Kart 64',
    'Super Mario Bros. 2',
    "Assassin's Creed IV: Black Flag",
    'Dune II: The Building of a Dynasty',
    'Panzer Dragoon Saga',
    'Missile Command',
    'Deltarune',
    'Frogger',
    'Dragon Quest VIII: Journey of the Cursed King',
    'The Stanley Parable',
    'Dragon Warrior',
    'Silent Hill',
    'Angry Birds',
    'Final Fantasy',
    'Sega Rally Championship',
    'Slay the Spire',
    'Her Story',
    'Contra III: The Alien Wars',
    'PaRappa the Rapper',
    'Mortal Kombat 11',
    "Demon's Souls",
    'The Legend of Zelda: Twilight Princess',
    'Arkanoid',
    'Perfect Dark',
    'Wipeout XL',
    'MULE',
    'Virtua Fighter 2',
    'Devil May Cry',
    'R-Type',
    'Phantasy Star Online',
    'Wave Race 64',
    'Hollow Knight',
    'Marvel Vs Capcom 2: New Age of Heroes',
    'God of War II',
    'Heroes of Might and Magic III',
    'MechWarrior 2',
    'Company of Heroes',
    'Diablo III',
    'Star Control II',
    "PlayerUnknown's Battlegrounds",
    'LittleBigPlanet',
    'Burnout Paradise',
    'The Sims 2',
    'Herzog Zwei',
    'Kentucky Route Zero',
    'Final Fantasy VIII',
    'Joust',
    'Breakout',
    'Marble Madness',
    'Metal Gear Solid V: The Phantom Pain',
    'Worms Armageddon',
    'Cuphead',
    'Animal Crossing: New Leaf',
    'Total Annihilation',
    'The Sims 3',
    'Hitman 2',
    'Valkyria Chronicles',
    'Alien: Isolation',
    'F-Zero GX',
    'Dungeon Master',
    'Crash Bandicoot: Warped',
    'F-Zero',
    'Dragon Age: Origins',
    'Tempest 2000',
    'Ultima',
    'Metal Slug',
    "Assassin's Creed Odyssey",
    'NBA 2K',
    'Life Is Strange',
    'Among Us',
    'Kingdom Hearts II',
    'Wizardry: Proving Grounds of the Mad Overlord',
    'Phoenix Wright: Ace Attorney',
    'Sonic and Knuckles',
    'Mega Man 3',
    'Final Fight',
    'Daytona USA',
    'Max Payne 2: The Fall of Max Payne',
    'Championship Manager',
    'OutRun 2',
    'Warlords',
    'Alone in the Dark',
    'Saturn Bomberman',
    'FTL: Faster Than Light',
    'NFL 2K',
    'Mass Effect 3',
    'Colossal Cave Adventure',
    'Bionic Commando',
    'Battlefield 2',
    "King's Quest",
    'Mega Man',
    'Call of Duty 2',
    'Crusader Kings II',
    'California Games',
    'Kingdom Hearts',
    'Alpha Centauri',
    'We Happy Few',
    'Worms',
    'A Mind Forever Voyaging',
    'Control',
    'Virtua Fighter 4',
    'Combat',
    'Virtua Fighter',
    'Shovel Knight',
    "Donkey Kong '94",
    'Star Wars: Jedi Knight - Dark Forces II',
    'Tekken 2',
    'Legacy of Kain: Soul Reaver',
    'Super Monkey Ball',
    'Rogue',
    'The Sentinel',
    'Fable',
    'Titanfall 2',
    'Bust-A-Move',
    'Tetris Attack',
    'Call of Duty',
    'Pac-Man Championship Edition',
    'Ultima III: Exodus',
    'Final Fantasy IX',
    'Freespace 2',
    'Ninja Gaiden (2004)',
    'Virtua Racing',
    'Sonic the Hedgehog 3',
    'Syndicate',
    'Twisted Metal 2',
    'Flower',
    'Ghouls N Ghosts',
    'God Hand',
    'Samurai Shodown',
    'Super Bomberman 2',
    'Star Wars: X-Wing vs TIE Fighter',
    'TowerFall',
    'God of War III',
    'Peggle',
    'Centipede',
    'The Operative: No One Lives Forever',
    'Virtua Tennis',
    'Mega Bomberman',
    'Snake',
    'Grand Theft Auto',
    'Elite Beat Agents',
    'Maniac Mansion',
    'Dig Dug',
    'Flashback',
    'Phantasy Star II',
    'Mother 3',
    "Assassin's Creed: Brotherhood",
    'Battlezone',
    'Sea of Thieves',
    'Impossible Mission',
    'Oddworld: Abe’s Oddyssee',
    'What Remains of Edith Finch',
    'The Chronicles of Riddick: Escape From Butcher Bay',
    'The Binding of Isaac',
    'Virtua Fighter 5',
    'Super Smash Bros. Brawl',
    'Tomb Raider II',
    'Zelda II: The Adventure of Link',
    'Dungeon Keeper',
    'Spacewar!',
    'The World Ends With You',
    'Pole Position',
    'Eve Online',
    'Fable II',
    'Ghosts N Goblins',
    'Track & Field',
    'Tetris Effect',
    "Dragon's Lair",
    'Unreal',
    'Cave Story',
    'Street Fighter Alpha 3',
    'Viewtiful Joe',
    'Borderlands',
    'Crash Bandicoot',
    'Archon: The Light and the Dark',
    'RollerCoaster Tycoon',
    "Castlevania III: Dracula's Curse",
    'Gran Turismo 2',
    'Ultima V: Warriors of Destiny',
    'Ultima VI: The False Prophet',
    'Jet Set Radio Future',
    'Forza Horizon 4',
    'Ridge Racer',
    'Gran Turismo 4',
    'Skies of Arcadia',
    'Grand Prix Legends',
    'Stunt Car Racer',
    'DuckTales',
    'Super Puzzle Fighter II Turbo',
    'Pac-Man Championship Edition DX',
    'Rayman 2: The Great Escape',
    'Guardian Heroes',
    'Lumines',
    'Super Mario Sunshine',
    'Earthworm Jim',
    'Chrono Cross',
    'Hot Shots Golf',
    'Manic Miner',
    'Final Fantasy XII',
    'Dragon Age: Inquisition',
    'Diddy Kong Racing',
    'Vanquish',
    'Bomberman',
    'Geometry Wars: Retro Evolved 2',
    'Final Fantasy XIV',
    'Super Castlevania IV',
    'Shinobi',
    "Dragon's Dogma",
    'Indiana Jones and the Fate of Atlantis',
    'Tempest',
    'Ultima II: The Revenge of the Enchantress',
    'Head Over Heels',
    'Pilotwings',
    'Ultima Underworld II: Labyrinth of Worlds',
    'Ultima VII Part Two: Serpent Isle',
    'Tomb Raider (2013)',
    'Guild Wars 2',
    'SimCity 3000',
    'Killer 7',
    'After Burner',
    'Wing Commander II: Vengeance of the Kilrathi',
    'NFL Blitz',
    'Defense of the Ancients',
    'Xenogears',
    'Boulderdash',
    "King's Quest VI: Heir Today, Gone Tomorrow",
    'Carmageddon',
    'Warcraft: Orcs & Humans',
    'Descent',
    'Snatcher',
    'Star Raiders',
    'System Shock',
    'International Karate +',
    'Vib Ribbon',
    'Shining Force II',
    'Hunt the Wumpus',
    "Tom Clancy's Rainbow Six",
    'NetHack',
    'Paper Mario: The Thousand-Year Door',
    'Super Mario Maker',
    "Conker's Bad Fur Day",
    'Paperboy',
    'Excitebike',
    'Paradroid',
    'Football Manager',
    'Vagrant Story',
    'Medal of Honor',
    'Teenage Mutant Ninja Turtles: Turtles in Time',
    "Kirby's Adventure",
    'Dr. Mario',
    'Harvest Moon',
    'Heavy Rain',
    "Wonder Boy III: The Dragon's Trap",
    'Theme Park',
    'The Witcher 2: Assassins of Kings',
    'Puyo Puyo',
    'Bastion',
    'Blood',
    'F-Zero X',
    'PGA Tour Golf',
    'Spy Hunter',
    '1080° Snowboarding',
    'Golden Axe',
    'Star Wars: Dark Forces',
    "Kirby's Dream Land",
    'Rainbow Islands: The Story of Bubble Bobble 2',
    'Bushido Blade',
    'The Curse of Monkey Island',
    'Micro Machines',
    'FS1 Flight Simulator',
    'Full Throttle',
    'Maze War',
    'Duck Hunt',
    'Space Channel 5',
    'The Last Express',
    'Grand Prix 2',
    "Donkey Kong Country 2: Diddy's Kong Quest",
    'Marvel Vs Capcom: Clash of Super Heroes',
    'Road Rash II',
    "The Bard's Tale",
    'Microsoft Flight Simulator',
    'Burnout Revenge',
    "Eternal Darkness: Sanity's Requiem",
    'Cannon Fodder',
    'Jet Set Willy',
    'Ecco the Dolphin',
    'Valkyrie Profile',
    'Frequency',
    'Mortal Kombat 3',
    'Samba De Amigo',
    'Defender of the Crown',
    'Computer Space',
    'Sonic Adventure',
    'Where in the World is Carmen Sandiego',
    'Gran Trak 10',
    'SSX 3',
    'Firewatch',
    'Galaxian',
    'Jagged Alliance 2',
    "Tom Clancy's Splinter Cell",
    'Crysis',
    'Shining Force',
    'Far Cry 3',
    'IL-2 Sturmovik',
    'Phantasy Star',
    'Phantasy Star III: Generations of Doom',
    'Quest For Glory: So You Want to Be a Hero',
    'Unreal Tournament 2004',
    'Zaxxon',
    'Cart Life',
    'Super Mario 3D World',
    "The Hitchhiker's Guide to the Galaxy",
    'Ant Attack',
    'ActRaiser',
    'Bully',
    'Strider',
    'Super Punch-Out!!',
    'DEFCON',
    "Devil's Crush",
    'Persona 3',
    'Demon Attack',
    'Wonder Boy',
    'Teenage Mutant Ninja Turtles',
    'Solitaire',
    'Minesweeper',
    'Mutant League Football',
    'Heretic',
    'Pinball Construction Set',
    'Habitat',
    'Aladdin',
    'Leisure Suit Larry in the Land of the Lounge Lizards',
    'Pokemon Black/White',
    '80 Days',
    "Michael Jackson's Moonwalker",
    'X-Men',
    'Battlefield: Bad Company 2',
    'Castle Wolfenstein',
    'Pokemon Ruby/Sapphire/Emerald',
    'R4: Ridge Racer Type 4',
    'Turrican II: The Final Fight',
    'Choplifter',
    'Colin McRae Rally 2.0',
    'Desert Strike',
    'Dragon Force',
    'Wizball',
    'Call of Duty: Modern Warfare 2',
    'Power Stone 2',
    'Blade Runner',
    'Qbert',
    'Mario Paint',
    'Road Rash',
    'Bejeweled',
    'ET: The Extra-Terrestrial',
    'Shadowrun',
    "Mario's Picross",
    'Panzer Dragoon',
    'Railroad Tycoon',
    'Aliens Versus Predator',
    'Super Star Wars',
    'Shenmue II',
    'Metal Gear',
    'Virtua Fighter 3',
    'Super Sprint',
    'Killer Instinct',
    'Monster Hunter 4 Ultimate',
    'Tenchu: Stealth Assassins',
    "You Don't Know Jack!",
    'Miner 2049er',
    'Metal Gear Solid 4: Guns of the Patriots',
    'Jungle Strike',
    'Yakuza 0',
    'Vampire: The Masquerade – Redemption',
    'Amnesia: The Dark Descent',
    'Terminator 2: The Arcade Game',
    'Wizardry VII: Crusaders of the Dark Savant',
    'Dwarf Fortress',
    'Metroid II: Return of Samus',
    'Pilotwings 64',
    'Game & Watch',
    'Spyro the Dragon',
    'Manhunt',
    'RC Pro-Am',
    'Karate Champ',
    'Paper Mario',
    'Nier',
    'Indy 500',
    'Capcom vs. SNK 2: Mark of the Millennium 2001',
    'Counter-Strike: Global Offensive',
    'Star Wars: Jedi Knight II - Jedi Outcast',
    "Oddworld: Abe's Exoddus",
    'River Raid',
    'Ori and the Blind Forest',
    'Falcon 3.0',
    'Exile',
    'Space Quest IV: Roger Wilco and the Time Rippers',
    'Command & Conquer: Red Alert 2',
    'Giants: Citizen Kabuto',
    'Tekken Tag Tournament',
    'Dead Space 2',
    'Puzzle Quest: Challenge of the Warlords',
    'Time Crisis',
    'Tennis For Two',
    'Deus Ex: Human Revolution',
    'Jumpman Junior',
    'Marathon',
    'SimCity 4',
    'Far Cry 2',
    'Command & Conquer: Tiberian Sun',
    'Twisted Metal',
    "Asheron's Call",
    'TimeSplitters 2',
    'Red Baron II',
    'Wonder Boy in Monster Land',
    'Operation Wolf',
    'Wing Commander III: Heart of the Tiger',
    'Resident Evil 3: Nemesis',
    'Mario Kart 7',
    'Bushido Blade 2',
    'Bust-A-Move 2',
    'Dead Rising',
    'Return Fire',
    'Super Monaco GP',
    'Master of Orion',
    'International Superstar Soccer',
    'Dark Souls II',
    'BeatMania',
    'Comanche: Maximum Overkill',
    'Mafia',
    'Super Mario Land 2: 6 Golden Coins',
    'Commandos: Behind Enemy Lines',
    'X-COM: Terror from the Deep',
    'Virtua Cop',
    'Myth: The Fallen Lords',
    'Baseball Stars',
    'AH-3 Thunderstrike',
    'Popeye',
    'Balance of Power',
    'WWF No Mercy',
    'Ratchet & Clank: Up Your Arsenal',
    'Forza Motorsport 4',
    'Lethal Enforcers',
    'Samurai Shodown II',
    'R-Type Final',
    'One-On-One',
    'Castle Crashers',
    'Star Control',
    'Resident Evil Code: Veronica',
    'Kid Icarus',
    "Mirror's Edge",
    'Medieval II: Total War',
    'Micro Machines 2: Turbo Tournament',
    'Xenon 2: Megablast',
    'Saints Row: The Third',
    'Knight Lore',
    'Lemonade Stand',
    'Math Blaster',
    'Marvel Vs Capcom 3: Fate of Two Worlds',
    'Ice Hockey',
    'Blaster Master',
    'Adventures of Lolo',
    'Super Off Road',
    "Bonk's Adventure",
    'Yo Noid',
    'The Simpsons',
    'Sunset Riders',
    'Jazz Jackrabbit',
    'Live A Live',
    'Links',
    'Spy vs Spy',
    "Pajama Sam: No Need to Hide When It's Dark Outside",
    'The House of the Dead',
    'Robotron X',
    'Snood',
    'X-Men Vs Street Fighter',
    'Turok: Dinosaur Hunter',
    'Doom 64',
    'MDK',
    'The King of Fighters 97',
    'Armored Core',
    'WCW Vs NWO: World Tour',
    'Bomberman 64',
    "Pajama Sam 2: Thunder and Lightning Aren't so Frightening",
    'WWF War Zone',
    'Star Wars: Rogue Squadron',
    "Spyro 2: Ripto's Rage!",
    'WCW/NWO Revenge',
    'Turok 2: Seeds of Evil',
    'Detective Barbie In the Mystery of the Carnival Caper!',
    'Destiny 2',
    'Rampart',
    'Mappy',
    'WarioWare: Twisted!',
    'Return to Castle Wolfenstein',
    'The Hobbit',
    'Moon Patrol',
    'Wasteland',
    'Metal Gear Solid: Peace Walker',
    'Prince of Persia 2: The Shadow and the Flame',
    'Theme Hospital',
    'Space Harrier',
    'Fantasy Zone II',
    'Legacy of the Wizard',
    'The Guardian Legend',
    'MUSHA',
    'Gimmick',
    'Dragon Quest V: Hand of the Heavenly Bride',
    'Final Fantasy V',
    'Violent Storm',
    'Castlevania: Rondo of Blood',
    'Gabriel Knight: Sins of the Father',
    'Batsugun',
    'Quest For Glory: Shadow of Darkness',
    'Windjammers',
    'Alien Vs Predator',
    'Puyo Puyo 2',
    'Realms of Arkania: Star Trail',
    "Demon's Crest",
    'Medal of Honor: Allied Assault',
    'Super C',
    'Last Ninja 2: Back With A Vengeance',
    'Vampire: The Masquerade – Bloodlines',
    'Cosmology of Kyoto',
    'Trials of Mana',
    'Battle Garegga',
    'Sexy Parodius',
    'Broken Sword: The Shadow of the Templars',
    'Tron',
    'Summer Games',
    'Twinkle Star Sprites',
    'Terranigma',
    'Gradius Gaiden',
    'Shock Troopers',
    'Darkstalkers 3',
    'Klonoa: Door to Phantomile',
    'Mega Man Legends',
    'The Last Blade 2',
    'Star Wars: Knights of the Old Republic II – The Sith Lords',
    'Hard Hat Mack',
    'Boulderdash 2',
    'Sega Rally 2',
    'The Ancient Art of War',
    'Turbo OutRun',
    'Starsiege: Tribes',
    'Urban Strike',
    'Turmoil',
    'Hitman 2: Silent Assassin',
    'Empire',
    'Space Race',
    'Spasim',
    'Shark Jaws',
    'Gun Fight',
    'Pedit5',
    'Heavyweight Champ',
    'Atari Football',
    'Orbit',
    'Space Panic',
    'Mario Bros.',
    'Populous II',
    'Ballblazer',
    'Disgaea: Hour of Darkness',
    'Buster Bros.',
    'Metal Slug 3',
    'Smash TV',
    'Ice Climber',
    'Rampage',
    'Mother',
    'Heroes of Might and Magic II',
    'DoDonPachi',
    'Realms of the Haunting',
    'Body Harvest',
    'Myth II: Soulblighter',
    'The Lurking Horror',
    'Qix',
    'Lunar Lander',
    'The Need For Speed',
    'NFL GameDay',
    'Mario Party',
    'Team Fortress Classic',
    'Star Wars: Episode I – Racer',
    'Out of the Park Baseball',
    'Persona 2: Innocent Sin',
    'Mario Golf',
    'Pokemon Snap',
    'Grand Theft Auto 2',
    'WWF WrestleMania 2000',
    'Underwurlde',
    'Kirby Super Star',
    'Tekken',
    'Panzer Dragoon II Zwei',
    'Dungeons & Dragons: Pool of Radiance',
    'Tactics Ogre: Let Us Cling Together',
    'R-Type Delta',
    'Garou: Mark of the Wolves',
    'World Series Baseball',
    'Fatal Frame II: Crimson Butterfly',
    'Gauntlet II',
    'Pokemon Go',
    'Donkey Kong Jr',
    'Jak and Daxter: The Precursor Legacy',
    'I Have No Mouth and I Must Scream',
    'The House of the Dead 2',
    'Kirby: Canvas Curse',
    'NCAA Football',
    'Discs of Tron',
    'Rave Racer',
    'Burnout 2: Point of Impact',
    'River City Ransom',
    'Point Blank 2',
    'Bomb Jack',
    'The Typing of the Dead',
    'SingStar',
    'Crimson Skies',
    'Mercenary',
    'Mystery House',
    'Arcanum: Of Steamworks and Magick Obscura',
    'Xevious',
    'Grid',
    'Star Wars: X-Wing Alliance',
    'Star Wars: Rogue Squadron II - Rogue Leader',
    "King's Quest II: Romancing the Throne",
    'Castlevania: Aria of Sorrow',
    "King's Quest III: To Heir Is Human",
    'Amplitude',
    'Koronis Rift',
    'Homeworld 2',
    'Skool Daze',
    'Sabre Wulf',
    '1942',
    'Dungeons & Dragons',
    'Uridium',
    'Deus Ex Machina',
    'Crossfire',
    "Lucifer's Realm",
    'MasterType',
    'Turbo',
    'The Arcade Machine',
    'Astro Chase',
    'Aztec',
    'Deadline',
    'Fort Apocalypse',
    "Ken Uston's Professional Blackjack",
    'Kid Grid',
    'The Mask of the Sun',
    'Millionaire: The Stock Market Simulation',
    'Night Mission Pinball',
    'Preppie',
    'Snooper Troops: Case #1 - The Granite Point Ghost',
    'Snooper Troops: Case #2 - The Case of the Disappearing Dolphin',
    "Spy's Demise",
    'Beach-Head',
    'Blue Max',
    'Combat Leader',
    'Drol',
    'Fax',
    'International Soccer',
    'Juice',
    'Jumpman',
    'Knights of the Desert',
    'Minit Man',
    'Murder by the Dozen',
    'Murder on the Zinderneuf',
    'Oil Barons',
    "Oil's Well",
    'Operation Whirlwind',
    'Pitstop',
    'Planetfall',
    'Pogo Joe',
    'Rally Speedway',
    'Repton',
    'Rescue Squad',
    'Sargon III',
    'Shamus: Case II',
    'Spare Change',
    'Star League Baseball',
    'The Witness (1983)',
    'Zombies',
    'Adventure Construction Set',
    'Agent USA',
    'Beyond Castle Wolfenstein',
    'Cutthroats',
    'Dimension X',
    'Dragonworld',
    'Earthly Delights',
    'Fahrenheit 451',
    'Intellectual Decathlon',
    'Mindshadow',
    'Rescue on Fractalus',
    'Run For the Money',
    'The Seven Cities of Gold',
    'Space Taxi',
    'SunDog: Frozen Legacy',
    'Suspect',
    'Timeship: Murder at the End of Time',
    'Xyphus',
    'Plants vs Zombies',
    'Hang-On',
    'The Way of the Exploding Fist',
    'Super Hang-On',
    "Castlevania II: Simon's Quest",
    'Kiwi Kraze',
    'Stunts',
    'Centurion: Defender of Rome',
    'Colorado',
    "King's Bounty",
    'Super Ghouls N Ghosts',
    'Commander Keen: Goodbye Galaxy!',
    'Choplifter II',
    'Dizzy: Prince of the Yolkfolk',
    'Gobliiins',
    # Late 1970s CP/M games, then small 1980s games. One title each.
    # A year is already on a name only when another game shares it.
    'Starfleet Orion',
    'Invasion Orion',
    'Temple of Apshai',
    'Datestones of Ryn',
    "Morloc's Tower",
    'Hellfire Warrior',
    'Rescue at Rigel',
    'Star Warrior',
    'Crush, Crumble and Chomp!',
    'Upper Reaches of Apshai',
    'Curse of Ra',
    'The Keys of Acheron',
    'Adventureland',
    'Pirate Adventure',
    'Secret Mission',
    'Voodoo Castle',
    'The Count',
    'Strange Odyssey',
    'Mystery Fun House',
    'Pyramid of Doom',
    'Ghost Town',
    'Savage Island',
    'Savage Island Part Two',
    'Golden Voyage',
    'Sorcerer of Claymorgue Castle',
    'Starcross',
    'Suspended',
    'Enchanter',
    'Infidel',
    'Sorcerer',
    'Seastalker',
    'Wishbringer',
    'Spellbreaker',
    'Ballyhoo',
    'Leather Goddesses of Phobos',
    'Trinity',
    'Moonmist',
    'Hollywood Hijinx',
    'Bureaucracy',
    'Stationfall',
    'Plundered Hearts',
    "Nord and Bert Couldn't Make Head or Tail of It",
    'Beyond Zork',
    'Border Zone',
    'Sherlock: The Riddle of the Crown Jewels',
    'Zork II',
    'Zork III',
    'Hamurabi',
    'Eliza',
    'Super Star Trek',
    'Ladder',
    'Sargon II',
    'Mychess',
    'Telengard',
    'Ali Baba and the Forty Thieves',
    'Dnieper River Line',
    'Pengo',
    'BurgerTime',
    'Berzerk',
    'Scramble',
    'Gorf',
    'Wizard of Wor',
    'Phoenix',
    'Venture',
    'Amidar',
    'Millipede',
    'Crystal Castles',
    'Food Fight',
    'Kangaroo',
    'Donkey Kong 3',
    'Elevator Action',
    'Jungle Hunt',
    'Tapper',
    'Mr. Do!',
    'Bosconian',
    'Yie Ar Kung-Fu',
    'Kung-Fu Master',
    'Gradius',
    'Life Force',
    'Chuckie Egg',
    'Jetpac',
    'Atic Atac',
    'Thrust',
    'Karateka',
    'Bruce Lee',
    'Archon',
    'Archon II: Adept',
    'M.U.L.E.',
    'Pitfall II: Lost Caverns',
    'H.E.R.O.',
    'Kaboom!',
    "Yars' Revenge",
    'Keystone Kapers',
    'Enduro',
    'Barnstorming',
    'Sinistar',
    'Stargate',
    'Frenzy',
    'Super Cobra',
    'Pac-Mania',
    'Jr. Pac-Man',
    'Super Pac-Man',
    'Pac-Land',
    'Balloon Fight',
    'Clu Clu Land',
    'Pooyan',
    'Lady Bug',
    'Front Line',
    'Rally-X',
    'Time Pilot',
    'Horace Goes Skiing',
    'Hungry Horace',
    'Lunar Jetman',
    'Back to Skool',
    'Alien 8',
    'Punch-Out!!',
    'Decathlon',
    'Winter Games',
    "Bump 'n' Jump",
    'Dig Dug II',
    'Pole Position II',
    "Mr. Do's Castle",
    'The Tower of Druaga',
    'Dragon Buster',
    'Gravitar',
    'Black Widow',
    'Major Havoc',
    'Moon Cresta',
    'Pleiads',
    'Bagman',
    'Mouse Trap',
    "Lock 'n' Chase",
    'Make Trax',
    'Zookeeper',
    "Satan's Hollow",
    'Crisis Mountain',
    'Mr. Robot and His Robot Factory',
    'Boulder Dash II',
    'Nebulus',
    'Klax',
    'Pipemania',
    'Cauldron',
    'Spellbound',
    'Pssst',
    'Transversion',
    "Hogan's Alley",
    'Wild Gunman',
    'Wrecking Crew',
    'Urban Champion',
    'Gyromite',
    'SonSon',
    'Commando',
    "Rush'n Attack",
    '1943',
    'TwinBee',
    'Jackal',
    'Fantasy Zone',
    'Out Run',
    'Altered Beast',
    'Renegade',
    'Barbarian: The Ultimate Warrior',
    'Rolling Thunder',
    'Blades of Steel',
    'One on One: Dr. J vs. Larry Bird',
    'The Great Escape',
    'Section Z',
    'Trojan',
    'Side Arms',
    'Chase H.Q.',
    'Xenophobe',
    "Toobin'",
    'Skate or Die',
    'Joust 2',
    'Questron',
    'Space Quest',
    'Gaplus',
    'Sky Kid',
    'Motos',
    # TRS-80, Commodore 64, and early Mac games that were not already listed.
    # TRS-80 and Commodore 64 titles are also in EIGHT_BIT. Early Mac titles are not.
    'Super Nova',
    'Galaxy Invasion',
    'Attack Force',
    'Cosmic Fighter',
    'Meteor Mission 2',
    'Robot Attack',
    'Defense Command',
    'Stellar Escort',
    'Weerd',
    'Bounceoids',
    'Armored Patrol',
    'Sea Dragon',
    'Android Nim',
    'Dancing Demon',
    'Bee Wary',
    'Scarfman',
    'Taipan',
    'Microchess',
    'Deathmaze 5000',
    'Asylum',
    'Asylum II',
    'Raaka-Tu',
    'Pyramid 2000',
    'Cytron Masters',
    'Dungeons of Daggorath',
    'Downland',
    'Mega-Bug',
    'Canyon Climber',
    'Time Bandit',
    'The Sands of Egypt',
    'Doubleback',
    'Reactoid',
    'Buzzard Bait',
    'Dallas Quest',
    'Calixto Island',
    'The Last Ninja',
    'Last Ninja 2',
    'Dropzone',
    'Pastfinder',
    'Beach-Head II',
    'Raid Over Moscow',
    "B.C.'s Quest for Tires",
    'Congo Bongo',
    'Spy vs. Spy: The Island Caper',
    'Ghostbusters',
    'Little Computer People',
    'The Great Giana Sisters',
    'Monty on the Run',
    'Auf Wiedersehen Monty',
    'Rick Dangerous',
    'Rick Dangerous 2',
    'Finders Keepers',
    'Nodes of Yesod',
    'Cybernoid',
    'Cybernoid II',
    'Sanxion',
    'Quedex',
    'Zynaps',
    'Armalyte',
    'Katakis',
    'Turrican',
    'Mayhem in Monsterland',
    'Impossible Mission II',
    'Zak McKracken and the Alien Mindbenders',
    'Neuromancer',
    'Project Firestart',
    'Rocket Ranger',
    'The Three Stooges',
    'King of Chicago',
    'Autoduel',
    'Phantasie',
    'Phantasie II',
    "Wizard's Crown",
    'The Eternal Dagger',
    'Legacy of the Ancients',
    'Silent Service',
    'F-15 Strike Eagle',
    'Solo Flight',
    'Hellcat Ace',
    'Airborne Ranger',
    'Racing Destruction Set',
    'Mail Order Monsters',
    'Heart of Africa',
    'Skyfox',
    'Raid on Bungeling Bay',
    'Bounty Bob Strikes Back',
    'Shamus',
    'Dino Eggs',
    'Serpentine',
    'Jawbreaker',
    'Leader Board',
    'World Class Leader Board',
    'Hardball',
    'Mean 18',
    'World Games',
    'Summer Games II',
    'Pitstop II',
    'The Games: Summer Edition',
    'Barbarian II: The Dungeon of Drax',
    'Target: Renegade',
    'Batman: The Movie',
    'RoboCop',
    'Platoon',
    'Laser Squad',
    'Driller',
    'The Lords of Midnight',
    'Gridrunner',
    'Attack of the Mutant Camels',
    'Sheep in Space',
    'Hover Bovver',
    'Iridis Alpha',
    'Alter Ego',
    'Test Drive',
    'Microprose Soccer',
    'Kick Off',
    'Ikari Warriors',
    'Speedball',
    'Ace of Aces',
    'Law of the West',
    'Psi-5 Trading Company',
    "David's Midnight Magic",
    'Lunar Leeper',
    'Cannonball Blitz',
    'Championship Lode Runner',
    'Dan Dare: Pilot of the Future',
    'Kikstart',
    'Buggy Boy',
    'Super Cycle',
    'Fight Night',
    'Killed Until Dead',
    'Grand Prix Circuit',
    'Indiana Jones and the Last Crusade',
    'Below the Root',
    'Myth: History in the Making',
    'Curse of the Azure Bonds',
    'Hillsfar',
    'Champions of Krynn',
    "The Bard's Tale II: The Destiny Knight",
    'Times of Lore',
    'Starflight',
    'Switchblade',
    'Pang',
    'Gunship',
    'Reach for the Stars',
    "BattleTech: The Crescent Hawk's Inception",
    'Tycoon: The Commodity Market Simulation',
    'Baron: The Real Estate Simulation',
    'Squire: The Financial Planning Simulation',
    'Enchanted Scepters',
    'Airborne!',
    'Dark Castle',
    'Beyond Dark Castle',
    'Crystal Quest',
    'Shufflepuck Cafe',
    'Glider',
    'Sky Shadow',
    "The Fool's Errand",
    'Shanghai',
    'The Ancient Art of War at Sea',
    'Patton Versus Rommel',
    'Strategic Conquest',
    'Empire: Wargame of the Century',
    'Falcon',
    'GATO',
    'Orbiter',
    'Deja Vu: A Nightmare Comes True',
    'Uninvited',
    'Shadowgate',
    'Deja Vu II: Lost in Las Vegas',
    'Quarterstaff',
    'The Colony',
    'Trust and Betrayal: The Legacy of Siboot',
    'Hidden Agenda',
    'The Manhole',
    'Cosmic Osmo and the Worlds Beyond the Mackerel',
    'Scarab of Ra',
    'Through the Looking Glass',
    'Apache Strike',
    'Stunt Copter',
    'Fokker Triplane',
    'Zork Zero',
    'Arthur: The Quest for Excalibur',
    "James Clavell's Shogun",
    'Loom',
    'Welltris',
)


def _synth():
    spec = importlib.util.spec_from_file_location("synth_html", HERE / "synth_html.py")
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    return mod


# 3D games. A second prompt asks for three.js. The plain prompt stays too.
THREE_JS = (
    "The Last of Us",
    "Half-Life 2",
    "The Legend of Zelda: Breath of the Wild",
    "The Witcher 3: Wild Hunt",
    "The Legend of Zelda: Ocarina of Time",
    "Super Mario 64",
    "Mass Effect 2",
    "BioShock",
    "Grand Theft Auto V",
    "Shadow of the Colossus",
    "God of War (2018)",
    "Call of Duty 4: Modern Warfare",
    "Red Dead Redemption",
    "Doom (1993)",
    "The Elder Scrolls V: Skyrim",
    "Halo: Combat Evolved",
    "GoldenEye 007",
    "Red Dead Redemption 2",
    "Bloodborne",
    "Metal Gear Solid",
    "Portal",
    "Uncharted 2: Among Thieves",
    "Journey",
    "Portal 2",
    "Minecraft",
    "Dark Souls",
    "Metroid Prime",
    "Deus Ex",
    "The Last of Us Part II",
    "Half-Life",
    "Counter-Strike",
    "Silent Hill 2",
    "Tomb Raider (1996)",
    "Ico",
    "Grand Theft Auto III",
    "Fallout 3",
    "Super Mario Odyssey",
    "Super Mario Galaxy 2",
    "System Shock 2",
    "Overwatch",
    "The Legend of Zelda: The Wind Waker",
    "Resident Evil",
    "Batman: Arkham Asylum",
    "Okami",
    "Grand Theft Auto IV",
    "Outer Wilds",
    "Prince of Persia: The Sands of Time",
    "Half-Life: Alyx",
    "Grand Theft Auto: Vice City",
    "Grand Theft Auto: San Andreas",
    "Fortnite",
    "Quake",
    "Assassin's Creed II",
    "God of War (2005)",
    "Left 4 Dead 2",
    "Burnout 3: Takedown",
    "Team Fortress 2",
    "Resident Evil 2",
    "Rocket League",
    "The Elder Scrolls IV: Oblivion",
    "Wolfenstein 3D",
    "Halo 3",
    "Dishonored",
    "The Legend of Zelda: Majora's Mask",
    "Thief: The Dark Project",
    "Spider-Man",
    "Left 4 Dead",
    "Quake III Arena",
    "Doom II",
    "Star Fox 64",
    "The Elder Scrolls III: Morrowind",
    "Halo 2",
    "Dead Space",
    "Gears of War",
    "Doom Eternal",
    "Fallout: New Vegas",
    "Mario Kart 64",
    "BioShock Infinite",
    "Sekiro: Shadows Die Twice",
    "Quake II",
    "Unreal Tournament",
    "The Legend of Zelda: Twilight Princess",
    "Perfect Dark",
    "Metal Gear Solid V: The Phantom Pain",
    "Alien: Isolation",
    "F-Zero GX",
    "Doom (2016)",
    "Duke Nukem 3D",
    "Horizon: Zero Dawn",
    "Control",
    "Titanfall 2",
    "Banjo-Kazooie",
    "Super Mario Galaxy",
    "Crash Bandicoot: Warped",
    "Star Fox",
    "Wipeout",
    "Mirror's Edge",
    "Turok: Dinosaur Hunter",
    "Return to Castle Wolfenstein",
    "Resident Evil 4",
)
# Pixel-art originals. The existing prompt gains one 8-bit sentence.
EIGHT_BIT = (
    "Tetris",
    "Street Fighter II",
    "Super Mario Bros. 3",
    "Super Mario World",
    "Super Mario Bros.",
    "Pokemon Blue/Red/Yellow",
    "Donkey Kong",
    "Ms. Pac-Man",
    "Pac-Man",
    "Mega Man 2",
    "Super Mario World 2: Yoshi's Island",
    "The Legend of Zelda",
    "Space Invaders",
    "Galaga",
    "Sonic the Hedgehog",
    "Contra",
    "Sonic the Hedgehog 2",
    "Pong",
    "Asteroids",
    "Double Dragon",
    "Metroid",
    "Defender",
    "Castlevania",
    "Ninja Gaiden (1988)",
    "Super Bomberman",
    "Mega Man X",
    "Bubble Bobble",
    "Gunstar Heroes",
    "Super Mario Bros. 2",
    "Missile Command",
    "Frogger",
    "Contra III: The Alien Wars",
    "Arkanoid",
    "R-Type",
    "Joust",
    "Breakout",
    "Metal Slug",
    "F-Zero",
    "Mega Man 3",
    "Final Fight",
    "Mega Man",
    "Ghouls N Ghosts",
    "Centipede",
    "Snake",
    "Dig Dug",
    "Zelda II: The Adventure of Link",
    "Mario Bros.",
    "Donkey Kong Jr",
    "Kid Icarus",
    "Blaster Master",
    "Popeye",
    "Moon Patrol",
    "Super Mario Land 2: 6 Golden Coins",
    "Gradius",
    "BurgerTime",
    "Berzerk",
    "Scramble",
    "Millipede",
    "Elevator Action",
    "Tapper",
    "Kung-Fu Master",
    "Pac-Land",
    "Balloon Fight",
    "Rally-X",
    "Time Pilot",
    "Commando",
    "1942",
    "1943",
    "Qix",
    "Lunar Lander",
    "Bomb Jack",
    "Xevious",
    "Super C",
    "Castlevania II: Simon's Quest",
    "Super Ghouls N Ghosts",
    "Pengo",
    "Phoenix",
    "Gauntlet",
    "Robotron 2084",
    "Pitfall!",
    "Prince of Persia",
    "OutRun",
    "Space Harrier",
    "Life Force",
    "Mike Tyson's Punch-Out!!",
    "Donkey Kong 3",
    "Mr. Do!",
    "Bosconian",
    "Yie Ar Kung-Fu",
    "Jetpac",
    "H.E.R.O.",
    "Kaboom!",
    "Yars' Revenge",
    "Sinistar",
    "Super Cobra",
    "Jungle Hunt",
    "Amidar",
    "Gorf",
    "Crystal Castles",
    "Ice Climber",
    # TRS-80 and Commodore 64 titles. Same strings as in TOP_GAMES.
    "Super Nova",
    "Galaxy Invasion",
    "Attack Force",
    "Cosmic Fighter",
    "Meteor Mission 2",
    "Robot Attack",
    "Defense Command",
    "Stellar Escort",
    "Weerd",
    "Bounceoids",
    "Armored Patrol",
    "Sea Dragon",
    "Android Nim",
    "Dancing Demon",
    "Bee Wary",
    "Scarfman",
    "Taipan",
    "Microchess",
    "Deathmaze 5000",
    "Asylum",
    "Asylum II",
    "Raaka-Tu",
    "Pyramid 2000",
    "Cytron Masters",
    "Dungeons of Daggorath",
    "Downland",
    "Mega-Bug",
    "Canyon Climber",
    "Time Bandit",
    "The Sands of Egypt",
    "Doubleback",
    "Reactoid",
    "Buzzard Bait",
    "Dallas Quest",
    "Calixto Island",
    "The Last Ninja",
    "Last Ninja 2",
    "Dropzone",
    "Pastfinder",
    "Beach-Head II",
    "Raid Over Moscow",
    "B.C.'s Quest for Tires",
    "Congo Bongo",
    "Spy vs. Spy: The Island Caper",
    "Ghostbusters",
    "Little Computer People",
    "The Great Giana Sisters",
    "Monty on the Run",
    "Auf Wiedersehen Monty",
    "Rick Dangerous",
    "Rick Dangerous 2",
    "Finders Keepers",
    "Nodes of Yesod",
    "Cybernoid",
    "Cybernoid II",
    "Sanxion",
    "Quedex",
    "Zynaps",
    "Armalyte",
    "Katakis",
    "Turrican",
    "Mayhem in Monsterland",
    "Impossible Mission II",
    "Zak McKracken and the Alien Mindbenders",
    "Neuromancer",
    "Project Firestart",
    "Rocket Ranger",
    "The Three Stooges",
    "King of Chicago",
    "Autoduel",
    "Phantasie",
    "Phantasie II",
    "Wizard's Crown",
    "The Eternal Dagger",
    "Legacy of the Ancients",
    "Silent Service",
    "F-15 Strike Eagle",
    "Solo Flight",
    "Hellcat Ace",
    "Airborne Ranger",
    "Racing Destruction Set",
    "Mail Order Monsters",
    "Heart of Africa",
    "Skyfox",
    "Raid on Bungeling Bay",
    "Bounty Bob Strikes Back",
    "Shamus",
    "Dino Eggs",
    "Serpentine",
    "Jawbreaker",
    "Leader Board",
    "World Class Leader Board",
    "Hardball",
    "Mean 18",
    "World Games",
    "Summer Games II",
    "Pitstop II",
    "The Games: Summer Edition",
    "Barbarian II: The Dungeon of Drax",
    "Target: Renegade",
    "Batman: The Movie",
    "RoboCop",
    "Platoon",
    "Laser Squad",
    "Driller",
    "The Lords of Midnight",
    "Gridrunner",
    "Attack of the Mutant Camels",
    "Sheep in Space",
    "Hover Bovver",
    "Iridis Alpha",
    "Alter Ego",
    "Test Drive",
    "Microprose Soccer",
    "Kick Off",
    "Ikari Warriors",
    "Speedball",
    "Ace of Aces",
    "Law of the West",
    "Psi-5 Trading Company",
    "David's Midnight Magic",
    "Lunar Leeper",
    "Cannonball Blitz",
    "Championship Lode Runner",
    "Dan Dare: Pilot of the Future",
    "Kikstart",
    "Buggy Boy",
    "Super Cycle",
    "Fight Night",
    "Killed Until Dead",
    "Grand Prix Circuit",
    "Indiana Jones and the Last Crusade",
    "Below the Root",
    "Myth: History in the Making",
    "Curse of the Azure Bonds",
    "Hillsfar",
    "Champions of Krynn",
    "The Bard's Tale II: The Destiny Knight",
    "Times of Lore",
    "Starflight",
    "Switchblade",
    "Pang",
    "Gunship",
    "Reach for the Stars",
    "BattleTech: The Crescent Hawk's Inception",
    "Tycoon: The Commodity Market Simulation",
    "Baron: The Real Estate Simulation",
    "Squire: The Financial Planning Simulation",
)
EIGHT_BIT_NOTE = " Use nice 8-bit graphics, as close to the original as possible."


# 2D games that need sprites, tile maps, and physics.
PHASER = (
    'Super Mario Bros.',
    'Super Mario Bros. 2',
    'Super Mario Bros. 3',
    'Super Mario World',
    "Super Mario World 2: Yoshi's Island",
    'Super Mario Land 2: 6 Golden Coins',
    'Mega Man',
    'Mega Man 2',
    'Mega Man 3',
    'Mega Man X',
    'Castlevania',
    "Castlevania II: Simon's Quest",
    'Castlevania: Symphony of the Night',
    'Castlevania: Rondo of Blood',
    'Castlevania: Aria of Sorrow',
    "Castlevania III: Dracula's Curse",
    'Super Castlevania IV',
    'Metroid',
    'Super Metroid',
    'Metroid II: Return of Samus',
    'Contra',
    'Contra III: The Alien Wars',
    'Super C',
    'Sonic the Hedgehog',
    'Sonic the Hedgehog 2',
    'Sonic the Hedgehog 3',
    'Sonic and Knuckles',
    'Sonic CD',
    'Celeste',
    'Hollow Knight',
    'Shovel Knight',
    'Cuphead',
    'Spelunky',
    'Spelunky 2',
    'Hotline Miami',
    'Super Meat Boy',
    'Streets of Rage 2',
    'Final Fight',
    'Double Dragon',
    'River City Ransom',
    'Metal Slug',
    'Metal Slug 3',
    'Gunstar Heroes',
    'The Legend of Zelda',
    'Zelda II: The Adventure of Link',
    'The Legend of Zelda: A Link to the Past',
    'The Legend of Zelda: Link’s Awakening',
    'EarthBound',
    'Undertale',
    'Chrono Trigger',
    'Secret of Mana',
    'Terranigma',
    'Ninja Gaiden (1988)',
    'Prince of Persia',
    'Prince of Persia 2: The Shadow and the Flame',
    'Flashback',
    'Out of This World',
    'Blaster Master',
    'Kid Icarus',
    'Ghouls N Ghosts',
    'Super Ghouls N Ghosts',
    'Ghosts N Goblins',
    'Ori and the Will of the Wisps',
    'Ori and the Blind Forest',
    'Hades',
    'The Binding of Isaac',
    'TowerFall',
    'Braid',
    'Fez',
    'Limbo',
    'Inside',
    'Street Fighter II',
    'Street Fighter III',
    'Street Fighter IV',
    'Street Fighter Alpha 3',
    'Mortal Kombat',
    'Mortal Kombat II',
    'Mortal Kombat 3',
    'X-Men Vs Street Fighter',
    'R-Type',
    'R-Type Final',
    'R-Type Delta',
    'Gradius',
    'Gradius Gaiden',
    'Life Force',
    '1942',
    '1943',
    'Xevious',
    'Ikaruga',
    'Gauntlet',
    'DuckTales',
    'Kirby Super Star',
    "Kirby's Adventure",
    "Kirby's Dream Land",
    'Oddworld: Abe’s Oddyssee',
    "Oddworld: Abe's Exoddus",
    'Commando',
    "Rush'n Attack",
    'Bionic Commando',
    'Altered Beast',
    'Super Bomberman',
    'Super Bomberman 2',
    'Mega Bomberman',
    'Saturn Bomberman',
    'Bomberman',
    'Moon Patrol',
    'Super Cobra',
    'Scramble',
    'Shinobi',
    'Golden Axe',
    'Strider',
    'Jackal',
    'Rolling Thunder',
    'TwinBee',
    'Fantasy Zone',
    'Fantasy Zone II',
    'Battle Garegga',
    'Batsugun',
    'DoDonPachi',
    'Wonder Boy',
    "Wonder Boy III: The Dragon's Trap",
    'Wonder Boy in Monster Land',
)
# Single-screen and simple sprite games. A renderer is enough.
PIXI = (
    'Tetris',
    'Pac-Man',
    'Ms. Pac-Man',
    'Galaga',
    'Galaxian',
    'Space Invaders',
    'Asteroids',
    'Centipede',
    'Missile Command',
    'Frogger',
    'Dig Dug',
    'Dig Dug II',
    'Breakout',
    'Arkanoid',
    'Pong',
    'Snake',
    'Bubble Bobble',
    'Joust',
    'Defender',
    'Robotron 2084',
    'Qix',
    'Lunar Lander',
    'Pengo',
    'BurgerTime',
    'Donkey Kong',
    'Mario Bros.',
    'Popeye',
    'Elevator Action',
    'Tapper',
    'Rally-X',
    'Time Pilot',
    'Millipede',
    'Phoenix',
    'Berzerk',
    'Amidar',
    'Gorf',
    'Crystal Castles',
    'Mr. Do!',
    'Bosconian',
    'Bomb Jack',
    'Pac-Land',
    'Balloon Fight',
    'Donkey Kong Jr',
    'Donkey Kong 3',
    'Mappy',
    'Paperboy',
    'Tempest 2000',
    'Marble Madness',
    'OutRun',
    'Space Harrier',
    'Zaxxon',
    'Jr. Pac-Man',
    'Super Pac-Man',
    'Dr. Mario',
    'Hang-On',
    'Super Hang-On',
    'After Burner',
)
# The game is the music or the rhythm.
HOWLER = (
    'Guitar Hero',
    'Rock Band',
    'Dance Dance Revolution',
    'PaRappa the Rapper',
    'Amplitude',
    'BeatMania',
    'Elite Beat Agents',
    'SingStar',
    'Rez',
    'The Typing of the Dead',
    'Lumines',
    'Vib Ribbon',
    'Space Channel 5',
    'Frequency',
    'Samba De Amigo',
)


def _with_note(line: str, note: str) -> str:
    return line.rstrip(".?") + "." + note


def _descriptor_rank(line: str) -> int:
    """Lower sorts first. Extra instructions outrank a plain title."""
    low = line.lower()
    if "three.js" in low:
        return 0
    if "8-bit" in low:
        return 1
    if " in phaser" in low or " in pixijs" in low or " in howler.js" in low:
        return 2
    return 3


def unique_prompts(home: list[str], titles: list[str]) -> list[str]:
    """One miniature prompt per top title, then home lines that are still new games.

    Pixel originals get an 8-bit sentence on that same line. 3D games get a three.js line. Other games get Phaser, PixiJS, or Howler.js
    when that library is the best fit. A game is in at most one of those.
    The returned list is sorted so three.js, then 8-bit, then the other libraries come first.
    """
    sh = _synth()
    out: list[str] = []
    seen: set[str] = set()
    n = len(OPENERS)
    eight = set(EIGHT_BIT)
    for i, title in enumerate(titles):
        body = f"a complete working version of {title}"
        plain = sh.subject_key(body)
        key = sh.subject_key(_with_note(body, EIGHT_BIT_NOTE)) if title in eight else plain
        if not key or key in seen or (plain and plain in seen):
            continue
        seen.add(key)
        if plain:
            seen.add(plain)
        line = OPENERS[i % n].format(body=body)
        if title in eight:
            line = _with_note(line, EIGHT_BIT_NOTE)
        out.append(line)
    for library, picked in (
        ("three.js", THREE_JS),
        ("Phaser", PHASER),
        ("PixiJS", PIXI),
        ("Howler.js", HOWLER),
    ):
        for j, title in enumerate(picked):
            body = f"a complete working version of {title} in {library}"
            key = sh.subject_key(body)
            if not key or key in seen:
                continue
            seen.add(key)
            out.append(OPENERS[j % n].format(body=body))
    for line in home:
        key = sh.subject_key(line)
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(line.strip())
    # Richest requests first, so a restart spends the GPU on them.
    # three.js, then the 8-bit line, then Phaser / PixiJS / Howler.js.
    out.sort(key=_descriptor_rank)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Write one prompt per game.")
    parser.add_argument("--src", type=Path, default=HERE / "ideas_1000.txt")
    parser.add_argument("--dest", type=Path, default=HERE / "ideas_3000.txt")
    args = parser.parse_args()
    home = []
    for line in args.src.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            home.append(s)
    lines = unique_prompts(home, list(TOP_GAMES))
    header = (
        "# One request per line. Each game or graphic appears once.\n"
        "# A complete working version of each top game, then ideas_1000.txt lines that are different.\n"
        "# Includes late 1970s CP/M games, TRS-80, Commodore 64, early Mac, and small 1980s games.\n"
        "# three.js lines first, then 8-bit, then other library lines, then the rest.\n"
        "# Built by expand_ideas.py. Openings vary. Do not hand-edit.\n"
    )
    args.dest.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(lines)} prompts -> {args.dest}")


if __name__ == "__main__":
    main()
