"""Background quality scoring for the small-model shards (CPU only, run niced).

Writes ~/MLX_Models/html_js_small/quality.sqlite, table quality(norm, weight).
train_small.py multiplies each doc's sampling weight by this value and rereads
the table at every checkpoint, so scores take effect while training runs.

Score mode (MLX venv: numpy + tokenizers). Each unique doc is decoded from its
shard once, then:
  - junk:      repeated-line ratio, "generated / do not edit" markers
  - syntax:    inline <script> / .js parsed by a long-lived node process
               (vm.Script / vm.SourceTextModule compile only, never executed)
  - near-dup:  64-perm MinHash on 5-word shingles, LSH 8 bands x 8 rows
               (~0.77 Jaccard); one doc per cluster is kept
  HTML docs with rank >= 1 are queued for browser mode.

Browser mode (harness venv: playwright). Loads queued HTML in CPU-only
headless Chromium, network blocked, 2 s run; page errors down-weight (only
for self-contained pages, since external <script src> cannot load), a
non-blank canvas up-weights.

Edu mode (MLX venv + torch, CPU). Scores JavaScript with the Stack-Edu
classifier (HuggingFaceTB/stack-edu-classifier-javascript, SmolLM2 paper);
for HTML only the inline <script> code is scored. Near-dups (weight 0) skip.

  nice -n 19 ~/Agents/.venv/bin/python quality_worker.py --workers 16
  nice -n 19 ~/Agent_learning/.venv/bin/python quality_worker.py --browser --workers 8
  nice -n 19 ~/Agents/.venv/bin/python quality_worker.py --edu --workers 12
Both resume; rerun score mode after new shards land.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import subprocess
import time
import zlib
from pathlib import Path

ROOT = Path(os.environ.get("SMALL_ROOT", "~/MLX_Models/html_js_small")).expanduser()
BASE = Path(os.environ.get("SMALL_BASE", "~/MLX_Models/MiniCPM5-1B-Base")).expanduser()
SHARDS = ROOT / "shards"
DB = ROOT / "quality.sqlite"

PERMS, BANDS = 64, 8
MAX_WORDS = 20_000
W_SYNTAX, W_REPEAT, W_GENERATED = 0.3, 0.3, 0.2
W_PAGE_ERROR, W_CANVAS_OK = 0.5, 1.5
# Stack-Edu score (0-5) -> weight. SmolLM2 kept >= 3; below 2 is mostly boilerplate.
EDU_WEIGHTS = ((1.5, 0.3), (2.5, 0.7), (3.5, 1.3), (9.9, 2.0))
EDU_MODEL = "HuggingFaceTB/stack-edu-classifier-javascript"

_WORD = re.compile(r"\w+")
_SCRIPT = re.compile(r"<script\b([^>]*)>(.*?)</script\s*>", re.S | re.I)
_GENERATED = re.compile(r"auto-?generated|do not edit|generated by", re.I)

# Syntax checker: one JSON array of {c: code, m: isModule} per line in, "1"/"0" out.
_NODE_CHECK = r"""
const vm = require('vm'); const rl = require('readline').createInterface({input: process.stdin});
function ok(c, m) {
  if (!m) { try { new vm.Script(c); return true; } catch (e) {} }
  try { new vm.SourceTextModule(c); return true; } catch (e) { return false; }
}
rl.on('line', l => { let r = 1; try { for (const s of JSON.parse(l)) if (!ok(s.c, s.m)) { r = 0; break; } } catch (e) {}
  process.stdout.write(r + '\n'); });
"""


def _db() -> sqlite3.Connection:
    # File check rebuilds the weight table while code quality is inserting.
    # 60s was not long enough for that rebuild, and the insert then failed.
    con = sqlite3.connect(DB, timeout=300)
    con.execute("pragma journal_mode=wal")
    con.executescript("""
        create table if not exists feat(norm text primary key, src text, rank int, ntok int,
                                        junk real, syntax int, sig blob);
        create table if not exists browser(norm text primary key, weight real);
        create table if not exists edu(norm text primary key, score real);
        create table if not exists pending_browser(norm text primary key, html text);
        create table if not exists done(shard text primary key);
        create table if not exists quality(norm text primary key, weight real);
    """)
    return con


# ---------------------------------------------------------------- score mode
_state: dict = {}


def _init_worker() -> None:
    import numpy as np
    from tokenizers import Tokenizer
    rng = np.random.default_rng(1234)
    _state["tok"] = Tokenizer.from_file(str(BASE / "tokenizer.json"))
    _state["a"] = rng.integers(1, 2**63, PERMS, dtype=np.uint64) | np.uint64(1)
    _state["b"] = rng.integers(0, 2**63, PERMS, dtype=np.uint64)
    _state["node"] = subprocess.Popen(["node", "--experimental-vm-modules", "--no-warnings", "-e", _NODE_CHECK],
                                      stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, bufsize=1)


def _minhash(text: str) -> bytes:
    import numpy as np
    words = _WORD.findall(text.lower())[:MAX_WORDS]
    if len(words) < 5:
        words = words + [""] * (5 - len(words))
    w = np.fromiter((zlib.crc32(x.encode()) for x in words), dtype=np.uint64, count=len(words))
    with np.errstate(over="ignore"):
        h = w[:-4] + w[1:-3] * np.uint64(1_000_003) + w[2:-2] * np.uint64(998_244_353) \
            + w[3:-1] * np.uint64(2_147_483_647) + w[4:] * np.uint64(4_294_967_291)
        sig = ((h[:, None] * _state["a"][None, :] + _state["b"][None, :]) >> np.uint64(32)).min(axis=0)
    return sig.astype(np.uint32).tobytes()


def _restart_node() -> None:
    """Node 25 aborts the syntax checker on some bad scripts. Start a fresh one."""
    old = _state.get("node")
    if old is not None and old.poll() is None:
        old.kill()
    _state["node"] = subprocess.Popen(
        ["node", "--experimental-vm-modules", "--no-warnings", "-e", _NODE_CHECK],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, bufsize=1)


def _syntax_ok(text: str, is_html: bool) -> int:
    if is_html:
        parts = []
        for attrs, body in _SCRIPT.findall(text):
            a = attrs.lower()
            if "src=" in a or not body.strip():
                continue
            t = re.search(r"type\s*=\s*['\"]?([\w/+-]+)", a)
            t = t.group(1) if t else "text/javascript"
            if t in ("text/javascript", "application/javascript", "module"):
                parts.append({"c": body, "m": t == "module"})
    else:
        parts = [{"c": text, "m": False}]
    if not parts:
        return 1
    # One crash must not kill the pool. Retry once; if that script kills node, count it as bad JS.
    for _ in range(2):
        p = _state["node"]
        try:
            p.stdin.write(json.dumps(parts) + "\n")
            p.stdin.flush()
            line = p.stdout.readline()
        except (BrokenPipeError, OSError):
            line = ""
        if line:
            return int(line.strip() or 1)
        _restart_node()
    return 0


def _junk(text: str) -> float:
    w = 1.0
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    if len(lines) >= 20 and len(set(lines)) < 0.5 * len(lines):
        w *= W_REPEAT
    if _GENERATED.search(text[:2000]):
        w *= W_GENERATED
    return w


def _score_shard(job: tuple[str, list[dict]]) -> tuple[str, list[tuple], list[tuple]]:
    import numpy as np
    shard, docs = job
    ids = np.memmap(SHARDS / f"{shard}.bin", dtype=np.uint32, mode="r") if docs else None
    rows, pending = [], []
    for d in docs:
        text = _state["tok"].decode(ids[d["offset"] + 1: d["offset"] + d["ntok"] - 1].tolist())
        is_html = d.get("lang", "HTML") == "HTML"
        rows.append((d["norm"], d["src"], d["rank"], d["ntok"], _junk(text),
                     _syntax_ok(text, is_html), _minhash(text)))
        if is_html and d["rank"] >= 1:
            pending.append((d["norm"], text))
    return shard, rows, pending


def _combine(con: sqlite3.Connection) -> dict:
    """LSH near-dup clusters + per-doc multipliers -> quality table."""
    import numpy as np
    feats = con.execute("select norm, src, rank, ntok, junk, syntax, sig from feat").fetchall()
    browser = dict(con.execute("select norm, weight from browser"))
    edu = {n: next(w for hi, w in EDU_WEIGHTS if s < hi) for n, s in con.execute("select norm, score from edu")}
    parent = list(range(len(feats)))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    sigs = np.frombuffer(b"".join(f[6] for f in feats), dtype=np.uint32).reshape(len(feats), PERMS)
    rows = PERMS // BANDS
    for b in range(BANDS):
        buckets: dict[bytes, int] = {}
        for i, key in enumerate(map(bytes, sigs[:, b * rows:(b + 1) * rows])):
            j = buckets.setdefault(key, i)
            if j != i:
                parent[find(i)] = find(j)
    # Keeper per cluster: own before gcc, then higher rank, then longer.
    key = lambda i: (feats[i][1] == "own", feats[i][2], feats[i][3])
    best: dict[int, int] = {}
    for i in range(len(feats)):
        r = find(i)
        if r not in best or key(i) > key(best[r]):
            best[r] = i
    keep = set(best.values())
    out, stats = [], {"docs": len(feats), "near_dup": 0, "syntax": 0, "junk": 0, "browser": 0, "edu": len(edu)}
    for i, (norm, src, _, _, junk, syntax, _) in enumerate(feats):
        # Edu score only reweights github-code-clean; own games are the target style.
        w = junk * (1.0 if syntax else W_SYNTAX) * browser.get(norm, 1.0) * (edu.get(norm, 1.0) if src == "gcc" else 1.0)
        if i not in keep:
            w, stats["near_dup"] = 0.0, stats["near_dup"] + 1
        stats["syntax"] += not syntax
        stats["junk"] += junk < 1.0
        stats["browser"] += norm in browser
        if w != 1.0:
            out.append((norm, w))
    with con:
        con.execute("delete from quality")
        con.executemany("insert into quality values (?, ?)", out)
    return stats


def score(workers: int) -> None:
    from multiprocessing import Pool
    con = _db()
    done = {r[0] for r in con.execute("select shard from done")}
    pending = [meta for meta in sorted(SHARDS.glob("*.jsonl")) if meta.stem not in done]
    # --follow calls this every few seconds. Nothing new: do not rebuild weights.
    if not pending:
        print("score: caught up", flush=True)
        con.close()
        return
    have = {r[0] for r in con.execute("select norm from feat")}
    jobs: dict[str, list[dict]] = {}
    shards = []
    for meta in pending:
        shards.append(meta.stem)
        for line in meta.read_text().splitlines():
            d = json.loads(line)
            if d["norm"] not in have:
                have.add(d["norm"])
                jobs.setdefault(meta.stem, []).append(d)
    print(f"score: {len(shards)} shards, {sum(map(len, jobs.values()))} new docs", flush=True)
    t0 = time.time()
    with Pool(workers, initializer=_init_worker) as pool:
        for i, (shard, rows, pending) in enumerate(
                pool.imap_unordered(_score_shard, [(s, jobs.get(s, [])) for s in shards]), 1):
            with con:
                con.executemany("insert or ignore into feat values (?,?,?,?,?,?,?)", rows)
                con.executemany("insert or ignore into pending_browser values (?,?)", pending)
                con.execute("insert or ignore into done values (?)", (shard,))
            if i % 10 == 0 or i == len(shards):
                print(f"{i}/{len(shards)} shards {time.time()-t0:.0f}s", flush=True)
    print("combine:", _combine(con), flush=True)
    con.close()


def follow(workers: int) -> None:
    """Score shards as the Stack download writes them. Stays up so the page does not show idle."""
    while True:
        score(workers)
        time.sleep(15)


def follow_browser(workers: int) -> None:
    """Run the browser pass whenever file check queues new pages."""
    while True:
        con = _db()
        n = con.execute("select count(*) from pending_browser").fetchone()[0]
        con.close()
        if n:
            browser(workers)
        else:
            time.sleep(60)


# -------------------------------------------------------------- browser mode
def browser(workers: int, batch: int = 200) -> None:
    import asyncio
    from playwright.async_api import async_playwright
    con = _db()

    async def check(ctx, html: str) -> float:
        # Blocked network: pages with <script src> fail for a missing file, not bad code.
        external = any("src=" in a.lower() for a, _ in _SCRIPT.findall(html))
        page = await ctx.new_page()
        errors: list[str] = []
        page.on("pageerror", lambda e: errors.append(str(e)))
        try:
            await page.set_content(html, timeout=5000, wait_until="load")
            await page.wait_for_timeout(2000)
            drawn = await page.evaluate("""() => [...document.querySelectorAll('canvas')].some(c => {
                try { const g = c.getContext('2d'); if (!g || !c.width || !c.height) return false;
                  const d = g.getImageData(0, 0, c.width, c.height).data;
                  for (let i = 4; i < d.length; i += 64) if (d[i] !== d[0] || d[i+1] !== d[1] || d[i+2] !== d[2]) return true;
                } catch (e) {} return false; })""")
        except Exception:
            return 1.0 if external else W_PAGE_ERROR
        finally:
            await page.close()
        if errors and not external:
            return W_PAGE_ERROR
        return W_CANVAS_OK if drawn else 1.0

    async def route(r) -> None:
        if r.request.url.startswith(("data:", "about:")):
            await r.continue_()
        else:
            await r.abort()

    async def run() -> None:
        async with async_playwright() as p:
            b = await p.chromium.launch(headless=True, args=["--disable-gpu", "--use-gl=swiftshader"])
            ctx = await b.new_context(viewport={"width": 800, "height": 600})
            await ctx.route("**/*", route)
            sem = asyncio.Semaphore(workers)

            async def one(norm: str, html: str) -> tuple[str, float]:
                async with sem:
                    return norm, await check(ctx, html)

            t0, n = time.time(), 0
            while True:
                rows = con.execute("select norm, html from pending_browser limit ?", (batch,)).fetchall()
                if not rows:
                    break
                res = await asyncio.gather(*(one(nm, h) for nm, h in rows))
                with con:
                    con.executemany("insert or replace into browser values (?, ?)", res)
                    con.executemany("delete from pending_browser where norm = ?", [(nm,) for nm, _ in rows])
                n += len(rows)
                print(f"browser: {n} pages {time.time()-t0:.0f}s", flush=True)
            await b.close()

    asyncio.run(run())


# ------------------------------------------------------------------ edu mode
def edu(threads: int, batch: int = 32, combine_every: int = 50_000) -> None:
    import numpy as np
    import torch
    from tokenizers import Tokenizer
    from transformers import AutoModelForSequenceClassification, AutoTokenizer
    torch.set_num_threads(threads)
    etok = AutoTokenizer.from_pretrained(EDU_MODEL)
    model = AutoModelForSequenceClassification.from_pretrained(EDU_MODEL).eval()
    tok = Tokenizer.from_file(str(BASE / "tokenizer.json"))
    con = _db()
    skip = {r[0] for r in con.execute("select norm from edu")}
    skip |= {r[0] for r in con.execute("select norm from quality where weight = 0")}
    t0, n, since = time.time(), 0, 0

    def flush(norms: list[str], texts: list[str]) -> None:
        x = etok(texts, truncation=True, max_length=512, padding=True, return_tensors="pt")
        with torch.inference_mode():
            s = model(**x).logits.squeeze(-1).float().tolist()
        with con:
            con.executemany("insert or replace into edu values (?, ?)", list(zip(norms, s)))

    for meta in sorted(SHARDS.glob("*.jsonl")):
        ids = np.memmap(meta.with_suffix(".bin"), dtype=np.uint32, mode="r")
        norms, texts = [], []
        try:
            for line in meta.read_text().splitlines():
                d = json.loads(line)
                if d["norm"] in skip or d["src"] != "gcc":  # own games are never edu-reweighted
                    continue
                skip.add(d["norm"])
                text = tok.decode(ids[d["offset"] + 1: d["offset"] + d["ntok"] - 1].tolist())
                if d.get("lang", "HTML") == "HTML":
                    text = "\n".join(b for a, b in _SCRIPT.findall(text) if "src=" not in a.lower() and b.strip())
                    if not text:
                        continue
                norms.append(d["norm"])
                texts.append(text[:8000])
                if len(norms) == batch:
                    flush(norms, texts)
                    n, since, norms, texts = n + batch, since + batch, [], []
                    if n % 2000 < batch:
                        print(f"edu: {n} docs {n / (time.time() - t0):.1f}/s", flush=True)
                    if since >= combine_every:
                        print("combine:", _combine(con), flush=True)
                        since = 0
            if norms:
                flush(norms, texts)
                n += len(norms)
        finally:
            # Close this shard before the next. Leaving them open dies once the download passes a few thousand.
            mapped = getattr(ids, "_mmap", None)
            if mapped is not None:
                mapped.close()
    print("combine:", _combine(con), flush=True)
    con.close()


def follow_edu(threads: int) -> None:
    """Keep scoring GitHub files. One pass exits when it reaches the last shard, including shards added later."""
    while True:
        edu(threads)
        time.sleep(20)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--workers", type=int, default=16)
    p.add_argument("--browser", action="store_true", help="run the Chromium pass (harness venv)")
    p.add_argument("--edu", action="store_true", help="Stack-Edu classifier pass (CPU torch threads = --workers)")
    p.add_argument("--follow", action="store_true", help="keep scoring new shards")
    p.add_argument("--follow-browser", action="store_true", help="keep checking newly queued pages")
    args = p.parse_args()
    ROOT.mkdir(parents=True, exist_ok=True)
    if args.follow and args.edu:
        follow_edu(args.workers)
    elif args.follow:
        follow(args.workers)
    elif args.follow_browser:
        follow_browser(args.workers)
    elif args.browser:
        browser(args.workers)
    elif args.edu:
        edu(args.workers)
    else:
        score(args.workers)


if __name__ == "__main__":
    main()
