"""Turn one HTML file into an agent-format training row.

Assistant is always <html_file> (real HTML + JavaScript). Files under
JMR_STORAGE use build_system_prompt(..., jmr_png_mode=True) — the same
/640png contract as chat.py. Every other download uses the default agent
prompt (full HTML/JS game pipeline). No plan-only rows.
"""
from __future__ import annotations

import hashlib
import html as html_lib
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path("/Users/jonathanrothberg/MLX_Models/html_game_sft")
# Canonical /640png examples (only these get jmr_png_mode in labels).
JMR_STORAGE = Path("/Users/jonathanrothberg/JMR-JS-CSS-FPGA-COMPUTER/storage")
AGENT = Path("/Users/jonathanrothberg/Agent_learning")
MODEL = Path("/Users/jonathanrothberg/MLX_Models/Qwen3.8-27B-mxfp8")
DB_PATH = ROOT / "games.sqlite"
# Train length is 8192. Re-measured 2026-09-21 after prompts_v1 shortened
# the /640png prompt: build_system_prompt(..., jmr_png_mode=True) is ~2200
# tokens (was ~3800). Chat-template overhead on the raw message text is
# ~16 tokens, so a row at 8128 still fits. Do not paste the prompt here.
TOKEN_BUDGET = 8128

sys.path.insert(0, str(AGENT))

from prompt_library import _TARGET_640PNG, _TARGET_640PNG_WIREFRAME  # noqa: E402
from prompts_v1 import build_system_prompt  # noqa: E402

_SYS_PNG = build_system_prompt("{goal}", jmr_png_mode=True)
# Full media-pipeline agent prompt (chat.py default, not /640 or /640png).
_SYS_GENERAL = build_system_prompt("{goal}")
_TOK = None

_BANNED = (
    (r"\bfetch\s*\(", "fetch"),
    (r"\bXMLHttpRequest\b", "xhr"),
    (r"\bimport\s", "import"),
    (r"\basync\b", "async"),
    (r"\bawait\b", "await"),
    (r"\beval\s*\(", "eval"),
    (r"\bWorker\s*\(", "worker"),
    (r"Audio\.play", "audio.play"),
    (r"three(?:\.js|\.min\.js)|\bTHREE\b", "three.js"),
    (r"\bWebGL\b|getContext\(\s*['\"]webgl", "webgl"),
    (r"\bMath\s*\.\s*sin\b", "Math.sin"),
    (r"\bMath\s*\.\s*cos\b", "Math.cos"),
    (r"\bMath\s*\.\s*atan2\b", "Math.atan2"),
    (r"\bperformance\s*\.\s*now\b", "performance.now"),
    (r"\bObject\s*\.\s*create\b", "Object.create"),
    (r"\bObject\s*\.\s*keys\b", "Object.keys"),
    (r"\bpreventDefault\b", "preventDefault"),
    (r"\b(?:Float|Uint|Int)32Array\b", "typed array"),
    (r"\bcharAt\b|\bcharCodeAt\b", "charAt"),
    (r"createElement\s*\(\s*['\"]canvas", "createElement canvas"),
    (r"\bglobalAlpha\b", "globalAlpha"),
    (r"\brgba\s*\(", "rgba"),
    (r"cdn\.|unpkg\.|jsdelivr", "cdn"),
    (r"jmr:spr:[\"']\s*\+", "built jmr:spr"),
    (r"\bsprite\s*\(", "sprite()"),
    (r"data:image", "data:image"),
)


def tokenizer():
    global _TOK
    if _TOK is None:
        from tokenizers import Tokenizer
        _TOK = Tokenizer.from_file(str(MODEL / "tokenizer.json"))
    return _TOK


def n_tokens(text: str) -> int:
    return len(tokenizer().encode(text).ids)


def looks_like_game(text: str) -> bool:
    """Any HTML that can be a game. Docs generators are the only skip.

    Canvas, requestAnimationFrame, an engine name, A-Frame, or a script
    tag all count. A js13k page that only does <script src="game.js">
    is still a game and must become a row.
    """
    if len(text) < 80:
        return False
    low = text.lower()
    if "generated by typedoc" in low or "generated by jsdoc" in low:
        return False
    if "<canvas" in low or "requestanimationframe" in low:
        return True
    if "a-scene" in low or "aframe" in low:
        return True
    if "<script" in low:
        return True
    if any(s in low for s in ("phaser", "pixi", "kaboom", "melonjs", "littlejs", "babylon", "kontra", "crafty")):
        return True
    return False


def _scripts(text: str) -> str:
    """Drop chrome-only host scripts before the mint lint."""
    return re.sub(
        r"<script[^>]*data-host\s*=\s*['\"]chrome['\"][^>]*>.*?</script>",
        "",
        text,
        flags=re.I | re.S,
    )


def lint_640png(text: str) -> list[str]:
    """Reasons this file is not a gold /640png label. Empty means gold."""
    body = _scripts(text)
    bad: list[str] = []
    low = body.lower()
    if not re.search(r"<canvas[^>]*width\s*=\s*['\"]640['\"]", body, re.I):
        bad.append("canvas width 640")
    if not re.search(r"<canvas[^>]*height\s*=\s*['\"]480['\"]", body, re.I):
        bad.append("canvas height 480")
    if "jmr:spr:" not in body:
        bad.append("jmr:spr literal")
    if "blitspr" not in low and "drawimage" not in low:
        bad.append("blitSpr/drawImage")
    if "window.state" not in body:
        bad.append("window.state")
    if "window.game" not in body:
        bad.append("window.game")
    if "requestanimationframe" not in low:
        bad.append("requestAnimationFrame")
    for pat, name in _BANNED:
        if re.search(pat, body, re.I):
            bad.append(name)
    return bad


def _title(text: str, path: Path) -> str:
    m = re.search(r"<title[^>]*>(.*?)</title>", text, re.I | re.S)
    if m:
        t = re.sub(r"\s+", " ", html_lib.unescape(m.group(1))).strip()
        if t:
            return t[:120]
    return path.stem.replace("-", " ").replace("_", " ")[:120]


def mechanic_card(text: str, path: Path) -> dict:
    title = _title(text, path)
    low = text.lower()
    keys = []
    for name, needle in (
        ("ArrowLeft", "arrowleft"),
        ("ArrowRight", "arrowright"),
        ("ArrowUp", "arrowup"),
        ("ArrowDown", "arrowdown"),
        ("Space", "space"),
        ("Enter", "enter"),
    ):
        if needle in low or name.lower() in low:
            keys.append(name)
    if not keys:
        keys = ["ArrowLeft", "ArrowRight", "Space"]
    return {
        "title": title,
        "keys": ", ".join(keys),
        "wireframe": "wireframe" in low,
    }


# three.js is allowed. The default agent prompt supports it. These other
# libraries are not what this LoRA is learning.
_ENGINE = re.compile(
    r"\bphaser\b|\bkaboom\s*\(|\bpixi\b|\bmelonjs\b|\bbabylon\b|"
    r"\ba-scene\b|\baframe\b|\bplaycanvas\b|\bcrafty\b|\bkontra\b|\blittlejs\b|"
    r"phaser\.js|kaboom\.js|pixi(\.min)?\.js",
    re.I,
)


def _inline_local_scripts(text: str, path: Path) -> str:
    """Pull sibling .js into the page so the label is one Chrome file."""

    def repl(match: re.Match) -> str:
        tag = match.group(0)
        if re.search(r"data-host\s*=\s*['\"]chrome['\"]", tag, re.I):
            return tag
        src_m = re.search(r"\bsrc\s*=\s*['\"]([^'\"]+)['\"]", tag, re.I)
        if not src_m:
            return tag
        src = src_m.group(1).split("?")[0].strip()
        if not src.lower().endswith(".js"):
            return tag
        if src.startswith(("http://", "https://", "//", "data:")):
            return tag
        js_path = (path.parent / src).resolve()
        try:
            if not js_path.is_file() or js_path.stat().st_size > 400_000:
                return tag
            body = js_path.read_text(encoding="utf-8", errors="replace").strip()
        except OSError:
            return tag
        if not body:
            return tag
        return f"<script>\n{body}\n</script>"

    return re.sub(r"<script\b[^>]*>\s*</script>", repl, text, flags=re.I)


# Real JavaScript in the page. A script tag that only loads analytics is not enough.
_JS_CODE = re.compile(
    r"\bfunction\b|\bconst\b|\blet\b|\bvar\b|=>|\bdocument\.|\bwindow\.|"
    r"\brequestAnimationFrame\b|\baddEventListener\b|\bgetContext\b",
    re.I,
)
# Not HTML+JavaScript. React, PHP, and Python do not belong in this set.
_NOT_HTML_JS = re.compile(
    r"\bimport\s+React\b|\bfrom\s+['\"]react['\"]|\bvue\.createApp\b|"
    r"\bangular\.module\b|<\?php|\bdef\s+\w+\s*\(|\bimport\s+torch\b",
    re.I,
)


def chrome_vanilla_html(text: str, path: Path) -> str | None:
    """One HTML document with real JavaScript, or None.

    Rejects library games, static pages, JSON-LD, and other languages.
    """
    if not re.search(r"<!doctype\s+html|<html[\s>]", text, re.I):
        return None
    if _ENGINE.search(text) or _NOT_HTML_JS.search(text):
        return None
    page = _inline_local_scripts(text, path)
    if _ENGINE.search(page) or _NOT_HTML_JS.search(page):
        return None
    parts: list[str] = []
    for attrs, body in re.findall(r"<script([^>]*)>([\s\S]*?)</script>", page, re.I):
        if re.search(r"type\s*=\s*['\"]application/(?:ld\+)?json['\"]", attrs, re.I):
            continue
        if re.search(r"googletagmanager|google-analytics|gtag\s*\(", body, re.I) and len(body) < 800:
            continue
        parts.append(body)
    js = "\n".join(parts)
    if len(js) < 80 or not _JS_CODE.search(js):
        return None
    return page


def has_javascript(text: str, path: Path) -> bool:
    """True when the page carries game logic (inline or local/external script)."""
    body = _scripts(text)
    low = body.lower()
    if re.search(r"<script[^>]*>[\s\S]{8,}?</script>", body, re.I):
        return True
    for m in re.finditer(r"<script[^>]+src\s*=\s*['\"]([^'\"]+)['\"]", body, re.I):
        src = m.group(1).split("?")[0].strip()
        if not src or src.startswith("data:"):
            continue
        if src.startswith("http://") or src.startswith("https://") or src.startswith("//"):
            return True
        js_path = (path.parent / src).resolve()
        try:
            if js_path.is_file() and js_path.stat().st_size > 20:
                return True
        except OSError:
            continue
    if "requestanimationframe" in low or "addEventListener" in body:
        return True
    return False


def _html_assistant(text: str, *, gold: bool) -> str:
    note = (
        "One 640x480 file. Quoted jmr:spr. blitSpr."
        if gold
        else "Complete HTML game file with canvas/script."
    )
    return (
        f"<think>\n{note}\n</think>\n"
        f"<html_file>\n{text.strip()}\n</html_file>\n"
    )


def _goal_png(card: dict) -> str:
    footer = _TARGET_640PNG_WIREFRAME if card["wireframe"] else _TARGET_640PNG
    return f"Build a one-screen game: {card['title']}. {footer}"


def _goal_general(card: dict) -> str:
    return f"Build a browser HTML5 game: {card['title']}."


def game_rank(line: str) -> int:
    """2 = a file we already know is a game, 1 = canvas or three.js game HTML, 0 = other.

    Looks only at the assistant HTML. The system prompt also mentions three.js
    and requestAnimationFrame, so the first <html_file> in the line is not the page.
    """
    if '"kind": "gold"' in line or '"kind":"gold"' in line:
        return 2
    if "/goodgame/" in line.lower():
        return 2
    cut = line.rfind("<html_file>")
    html = line[cut:].lower() if cut >= 0 else ""
    has_canvas = "<canvas" in html or "getcontext" in html
    has_loop = "requestanimationframe" in html
    has_three = "three.js" in html or "three.min.js" in html or "new three." in html
    if has_three or (has_canvas and has_loop):
        return 1
    return 0


def is_jmr_storage(path: Path) -> bool:
    """True for canonical JMR /640png HTML under storage/."""
    try:
        return path.resolve().is_relative_to(JMR_STORAGE.resolve())
    except (ValueError, OSError):
        return False


def _pack(system: str, goal: str, page: str, *, gold: bool, kind: str, title: str, path: Path, part: int) -> dict | None:
    assistant = _html_assistant(page, gold=gold)
    if n_tokens(system + "\n" + goal + "\n" + assistant) > TOKEN_BUDGET:
        return None
    digest = hashlib.sha256(f"{path}:{part}:".encode() + page.encode("utf-8", errors="replace")).hexdigest()
    return {
        "sha": digest,
        "kind": kind,
        "title": title,
        "source": str(path),
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": goal},
            {"role": "assistant", "content": assistant},
        ],
    }


def _pieces(page: str, room: int) -> list[str]:
    """Split a long /640png file into pieces that fit the train window."""
    ids = tokenizer().encode(page).ids
    if len(ids) <= room:
        return [page]
    step = max(256, room - 64)
    out = []
    for i in range(0, len(ids), step):
        piece = tokenizer().decode(ids[i:i + step])
        # decode can re-expand. Drop the tail until this piece fits.
        while piece and n_tokens(piece) > room:
            piece = piece[: max(1, int(len(piece) * 0.9))]
        if piece.strip():
            out.append(piece)
    return out


def training_rows(text: str, path: Path) -> list[dict]:
    """Rows for one file. JMR storage is always /640png, games and tools alike."""
    if is_jmr_storage(path):
        card = mechanic_card(text, path)
        goal = _goal_png(card)
        system = _SYS_PNG.replace("{goal}", goal)
        overhead = n_tokens(system + "\n" + goal + "\n" + _html_assistant("", gold=True))
        room = TOKEN_BUDGET - overhead - 8
        rows = []
        for part, piece in enumerate(_pieces(text, max(256, room))):
            row = _pack(system, goal, piece, gold=True, kind="gold", title=card["title"], path=path, part=part)
            if row:
                rows.append(row)
        return rows
    if not looks_like_game(text) or not has_javascript(text, path):
        return []
    page = chrome_vanilla_html(text, path)
    if page is None:
        return []
    card = mechanic_card(page, path)
    goal = _goal_general(card)
    system = _SYS_GENERAL.replace("{goal}", goal)
    # Long games stay in the set. Split them so the train window can hold each piece.
    overhead = n_tokens(system + "\n" + goal + "\n" + _html_assistant("", gold=False))
    room = max(256, TOKEN_BUDGET - overhead - 8)
    rows = []
    for part, piece in enumerate(_pieces(page, room)):
        row = _pack(system, goal, piece, gold=False, kind="html", title=card["title"], path=path, part=part)
        if row:
            rows.append(row)
    return rows


def messages_for_html(text: str, path: Path) -> dict | None:
    """First training row, or None. Prefer training_rows when a file splits."""
    rows = training_rows(text, path)
    return rows[0] if rows else None


def connect() -> sqlite3.Connection:
    ROOT.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=60)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute(
        """CREATE TABLE IF NOT EXISTS games (
            sha TEXT PRIMARY KEY,
            path TEXT,
            title TEXT,
            kind TEXT,
            bytes INTEGER
        )"""
    )
    return conn


def already(conn: sqlite3.Connection, sha: str) -> bool:
    row = conn.execute("SELECT 1 FROM games WHERE sha=?", (sha,)).fetchone()
    return row is not None
